/**
 * Seal wallet routes — proxy to on-chain wallet operations.
 *
 * These endpoints prepare unsigned transactions that the Flutter app
 * signs via MWA (Mobile Wallet Adapter) and submits. The user always
 * pays for rent and transaction fees.
 */

import { Hono } from "hono";
import { z } from "zod";
import { zValidator } from "@hono/zod-validator";
import {
  PublicKey,
  Transaction,
  SystemProgram,
  Keypair,
  LAMPORTS_PER_SOL,
} from "@solana/web3.js";
import {
  ASSOCIATED_TOKEN_PROGRAM_ID,
  TOKEN_2022_PROGRAM_ID,
  TOKEN_PROGRAM_ID,
} from "@solana/spl-token";
import {
  getConnection,
  deriveWalletPda,
  deriveAgentPda,
  deriveSessionPda,
  SEAL_PROGRAM_ID,
  withRpcRetry,
} from "../services/solana.js";
import { TransactionSender } from "../engine/transaction-sender.js";
// Sponsor wallet removed — users pay for their own transactions.
import { requireAuth, type AuthVariables } from "../middleware/auth.js";
import { createApiError } from "../middleware/error.js";
import config from "../config.js";
import db from "../db/index.js";
import { users, bots } from "../db/schema.js";
import { eq, and, isNotNull } from "drizzle-orm";

const wallet = new Hono<{ Variables: AuthVariables }>();

// ═══════════════════════════════════════════════════════════════
// Schemas
// ═══════════════════════════════════════════════════════════════

const createWalletSchema = z.object({
  dailyLimitSol: z.number().positive().max(1000).default(10),
  perTxLimitSol: z.number().positive().max(100).default(1),
});

const createAndFundSchema = z.object({
  dailyLimitSol: z.number().positive().max(1000).default(10),
  perTxLimitSol: z.number().positive().max(100).default(1),
  depositSol: z.number().positive().max(1000),
});

const depositSchema = z.object({
  amountSol: z.number().positive().max(1000),
});

const registerAgentSchema = z.object({
  /** Bot ID (8-char hex) to register as a Seal agent */
  botId: z.string().regex(/^[0-9a-f]{8}$/),
  /** Agent keypair public key (base58) — generated by the Flutter app */
  agentPubkey: z.string().min(32).max(50),
  /** Human-readable name for the agent (max 32 chars) */
  name: z.string().max(32).default("Sage Bot Agent"),
  /** Maximum SOL the agent can spend per day */
  dailyLimitSol: z.number().positive().max(1000).default(5),
  /** Maximum SOL the agent can spend per transaction */
  perTxLimitSol: z.number().positive().max(100).default(1),
  /** Additional program IDs to allow beyond backend defaults */
  allowedPrograms: z.array(z.string().min(32).max(50)).max(16).optional(),
});

const createSessionSchema = z.object({
  /** Bot ID that owns the agent for this session */
  botId: z.string().regex(/^[0-9a-f]{8}$/),
  /** Ephemeral session keypair pubkey (base58) — generated client-side */
  sessionPubkey: z.string().min(32).max(50),
  /** Session duration in seconds (max 7 days) */
  durationSecs: z.number().int().positive().max(7 * 24 * 60 * 60).default(24 * 60 * 60),
  /** Maximum SOL this session can spend total */
  maxAmountSol: z.number().positive().max(1000).default(5),
  /** Maximum SOL per individual transaction */
  maxPerTxSol: z.number().positive().max(100).default(1),
});

const revokeSessionSchema = z.object({
  /** Bot ID whose session to revoke */
  botId: z.string().regex(/^[0-9a-f]{8}$/),
});

// ═══════════════════════════════════════════════════════════════
// Discriminators & Account Parsing (from seal backend)
// ═══════════════════════════════════════════════════════════════

const SMART_WALLET_DISCRIMINATOR = Buffer.from("SealWalt");

function readU64LE(buf: Buffer, offset: number): bigint {
  return buf.readBigUInt64LE(offset);
}

function readI64LE(buf: Buffer, offset: number): bigint {
  return buf.readBigInt64LE(offset);
}

function readPubkey(buf: Buffer, offset: number): string {
  return new PublicKey(buf.subarray(offset, offset + 32)).toBase58();
}

interface SmartWalletState {
  address: string;
  pdaAuthority: string;
  owner: string;
  bump: number;
  nonce: string;
  agentCount: number;
  guardianCount: number;
  recoveryThreshold: number;
  guardians: string[];
  dailyLimitSol: number;
  perTxLimitSol: number;
  spentTodaySol: number;
  dayStartTimestamp: number;
  isLocked: boolean;
  isClosed: boolean;
}

const MEMO_PROGRAM_ID = new PublicKey(
  "MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr"
);

const CORE_AGENT_ALLOWED_PROGRAMS = [
  SystemProgram.programId,
  TOKEN_PROGRAM_ID,
  TOKEN_2022_PROGRAM_ID,
  ASSOCIATED_TOKEN_PROGRAM_ID,
  MEMO_PROGRAM_ID,
];

function parseConfiguredProgramIds(value?: string): PublicKey[] {
  if (!value) return [];

  return value
    .split(",")
    .map((programId) => programId.trim())
    .filter(Boolean)
    .map((programId) => new PublicKey(programId));
}

function uniquePubkeys(programs: PublicKey[]): PublicKey[] {
  const seen = new Set<string>();
  return programs.filter((program) => {
    const key = program.toBase58();
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

function getConfiguredAgentAllowlist(): PublicKey[] {
  const clusterSpecific =
    config.SOLANA_NETWORK === "mainnet-beta"
      ? config.SEAL_ALLOWED_PROGRAMS_MAINNET
      : config.SEAL_ALLOWED_PROGRAMS_DEVNET;

  return uniquePubkeys([
    ...CORE_AGENT_ALLOWED_PROGRAMS,
    ...parseConfiguredProgramIds(config.SEAL_ALLOWED_PROGRAMS),
    ...parseConfiguredProgramIds(clusterSpecific),
  ]);
}

function resolveAgentAllowedPrograms(extraPrograms?: string[]): PublicKey[] {
  const requestedPrograms = (extraPrograms ?? []).map(
    (programId) => new PublicKey(programId)
  );

  const allowedPrograms = uniquePubkeys([
    ...getConfiguredAgentAllowlist(),
    ...requestedPrograms,
  ]);

  const hasProtocolSpecificProgram = allowedPrograms.some(
    (program) =>
      !CORE_AGENT_ALLOWED_PROGRAMS.some((core) => core.equals(program))
  );

  if (!hasProtocolSpecificProgram) {
    throw createApiError(
      "Seal agent allowlist must include at least one protocol program. Configure SEAL_ALLOWED_PROGRAMS_MAINNET/DEVNET or pass allowedPrograms explicitly.",
      400
    );
  }

  return allowedPrograms;
}

async function getCanonicalWalletPda(
  userId: number,
  ownerPubkey: PublicKey,
  options?: { allowDerivedFallback?: boolean }
): Promise<PublicKey> {
  const [user] = await db
    .select({ sealWalletAddress: users.sealWalletAddress })
    .from(users)
    .where(eq(users.id, userId));

  if (user?.sealWalletAddress) {
    return new PublicKey(user.sealWalletAddress);
  }

  if (options?.allowDerivedFallback === false) {
    throw createApiError("Seal wallet address is not recorded for this user.", 409);
  }

  const [walletPda] = deriveWalletPda(ownerPubkey);
  return walletPda;
}

function parseSmartWallet(
  address: string,
  data: Buffer
): SmartWalletState | null {
  if (data.length < 278) return null;
  const disc = data.subarray(0, 8);
  if (!disc.equals(SMART_WALLET_DISCRIMINATOR)) return null;

  const guardianCount = data[82];
  const guardians: string[] = [];
  for (let i = 0; i < guardianCount && i < 5; i++) {
    guardians.push(readPubkey(data, 84 + i * 32));
  }

  return {
    address,
    pdaAuthority: readPubkey(data, 8),
    owner: readPubkey(data, 40),
    bump: data[72],
    nonce: readU64LE(data, 73).toString(),
    agentCount: data[81],
    guardianCount,
    recoveryThreshold: data[83],
    guardians,
    dailyLimitSol: Number(readU64LE(data, 244)) / LAMPORTS_PER_SOL,
    perTxLimitSol: Number(readU64LE(data, 252)) / LAMPORTS_PER_SOL,
    spentTodaySol: Number(readU64LE(data, 260)) / LAMPORTS_PER_SOL,
    dayStartTimestamp: Number(readI64LE(data, 268)),
    isLocked: data[276] !== 0,
    isClosed: data[277] !== 0,
  };
}

// ═══════════════════════════════════════════════════════════════
// Instruction Builder
// ═══════════════════════════════════════════════════════════════

function encodeU64(value: bigint): Buffer {
  const buf = Buffer.alloc(8);
  buf.writeBigUInt64LE(value);
  return buf;
}

function buildCreateWalletIx(
  funder: PublicKey,
  owner: PublicKey,
  walletPda: PublicKey,
  bump: number,
  dailyLimitLamports: bigint,
  perTxLimitLamports: bigint
) {
  const data = Buffer.concat([
    Buffer.from([0]), // CreateWallet discriminant
    Buffer.from([bump]),
    encodeU64(dailyLimitLamports),
    encodeU64(perTxLimitLamports),
  ]);

  return {
    programId: SEAL_PROGRAM_ID,
    keys: [
      { pubkey: funder, isSigner: true, isWritable: true },
      { pubkey: owner, isSigner: true, isWritable: false },
      { pubkey: walletPda, isSigner: false, isWritable: true },
      {
        pubkey: SystemProgram.programId,
        isSigner: false,
        isWritable: false,
      },
    ],
    data,
  };
}

// ═══════════════════════════════════════════════════════════════
// Routes (all require auth)
// ═══════════════════════════════════════════════════════════════

/**
 * POST /wallet/prepare-create
 * Prepare TX for Seal wallet creation. User pays rent + fees.
 */
wallet.post(
  "/prepare-create",
  requireAuth,
  zValidator("json", createWalletSchema),
  async (c) => {
    const ownerAddress = c.var.walletAddress;
    const body = c.req.valid("json");
    const ownerPubkey = new PublicKey(ownerAddress);

    const [walletPda, bump] = deriveWalletPda(ownerPubkey);

    // Check if wallet already exists (with retry for flaky RPC)
    const connection = getConnection();
    const existing = await withRpcRetry(() =>
      connection.getAccountInfo(walletPda)
    );
    if (existing) {
      throw createApiError("Seal wallet already exists", 409, {
        walletAddress: walletPda.toBase58(),
      });
    }

    const dailyLimitLamports = BigInt(
      Math.floor(body.dailyLimitSol * LAMPORTS_PER_SOL)
    );
    const perTxLimitLamports = BigInt(
      Math.floor(body.perTxLimitSol * LAMPORTS_PER_SOL)
    );

    const ix = buildCreateWalletIx(
      ownerPubkey,
      ownerPubkey,
      walletPda,
      bump,
      dailyLimitLamports,
      perTxLimitLamports
    );

    const { blockhash, lastValidBlockHeight } =
      await withRpcRetry(() => connection.getLatestBlockhash());

    const tx = new Transaction();
    tx.add(ix);
    tx.recentBlockhash = blockhash;
    tx.feePayer = ownerPubkey;

    const serialized = tx
      .serialize({ requireAllSignatures: false })
      .toString("base64");

    // Store seal wallet address in user record
    await db.update(users)
      .set({ sealWalletAddress: walletPda.toBase58() })
      .where(eq(users.walletAddress, ownerAddress));

    return c.json({
      success: true,
      walletAddress: walletPda.toBase58(),
      transaction: serialized,
      sponsored: false,
      network: config.SOLANA_NETWORK,
      blockhash,
      lastValidBlockHeight,
    });
  }
);

/**
 * GET /wallet/state
 * Get authenticated user's Seal wallet state.
 */
wallet.get("/state", requireAuth, async (c) => {
  const userId = c.var.userId;
  const ownerAddress = c.var.walletAddress;
  const ownerPubkey = new PublicKey(ownerAddress);
  const walletPda = await getCanonicalWalletPda(userId, ownerPubkey);

  const connection = getConnection();
  const accountInfo = await withRpcRetry(() =>
    connection.getAccountInfo(walletPda)
  );

  if (!accountInfo) {
    return c.json({
      success: true,
      exists: false,
      walletAddress: walletPda.toBase58(),
    });
  }

  const walletState = parseSmartWallet(
    walletPda.toBase58(),
    accountInfo.data as Buffer
  );

  return c.json({ success: true, exists: true, wallet: walletState });
});

/**
 * GET /wallet/balance
 * Get SOL balance of authenticated user's Seal wallet.
 */
wallet.get("/balance", requireAuth, async (c) => {
  const userId = c.var.userId;
  const ownerAddress = c.var.walletAddress;
  const ownerPubkey = new PublicKey(ownerAddress);
  const walletPda = await getCanonicalWalletPda(userId, ownerPubkey);

  const connection = getConnection();
  const walletLamports = await connection.getBalance(walletPda);

  // Include session signer balances — older deposits may have been
  // routed to session signers before the TransferLamports upgrade.
  // New deposits go to the wallet PDA; the backend pre-funds the 
  // session signer on-demand via TransferLamports before each trade.
  let sessionLamports = 0;
  try {
    const sessionRows = await db
      .select({ sessionPubkey: bots.sessionPubkey })
      .from(bots)
      .where(and(
        eq(bots.userId, userId),
        eq(bots.mode, "live"),
        isNotNull(bots.sessionPubkey),
      ));
    const seen = new Set<string>();
    for (const row of sessionRows) {
      if (!row.sessionPubkey || seen.has(row.sessionPubkey)) continue;
      seen.add(row.sessionPubkey);
      try {
        sessionLamports += await connection.getBalance(new PublicKey(row.sessionPubkey));
      } catch { /* skip invalid keys */ }
    }
  } catch { /* ignore */ }

  const totalLamports = walletLamports + sessionLamports;

  return c.json({
    success: true,
    lamports: totalLamports,
    sol: totalLamports / LAMPORTS_PER_SOL,
    walletLamports,
    sessionLamports,
  });
});

/**
 * POST /wallet/prepare-create-and-fund
 * Prepare a TX that creates a Seal wallet AND transfers SOL into it.
 * User pays for everything (rent + deposit + fees).
 */
wallet.post(
  "/prepare-create-and-fund",
  requireAuth,
  zValidator("json", createAndFundSchema),
  async (c) => {
    const ownerAddress = c.var.walletAddress;
    const body = c.req.valid("json");
    const ownerPubkey = new PublicKey(ownerAddress);

    const [walletPda, bump] = deriveWalletPda(ownerPubkey);

    // Check if wallet already exists
    const connection = getConnection();
    const existing = await withRpcRetry(() =>
      connection.getAccountInfo(walletPda)
    );
    if (existing) {
      throw createApiError("Seal wallet already exists", 409, {
        walletAddress: walletPda.toBase58(),
      });
    }

    const dailyLimitLamports = BigInt(
      Math.floor(body.dailyLimitSol * LAMPORTS_PER_SOL)
    );
    const perTxLimitLamports = BigInt(
      Math.floor(body.perTxLimitSol * LAMPORTS_PER_SOL)
    );
    const depositLamports = BigInt(
      Math.floor(body.depositSol * LAMPORTS_PER_SOL)
    );

    // Instruction 1: Create wallet PDA
    const createIx = buildCreateWalletIx(
      ownerPubkey,
      ownerPubkey,
      walletPda,
      bump,
      dailyLimitLamports,
      perTxLimitLamports
    );

    // Instruction 2: Transfer SOL from user → wallet PDA
    const transferIx = SystemProgram.transfer({
      fromPubkey: ownerPubkey,
      toPubkey: walletPda,
      lamports: depositLamports,
    });

    const { blockhash, lastValidBlockHeight } =
      await withRpcRetry(() => connection.getLatestBlockhash());

    const tx = new Transaction();
    tx.add(createIx);
    tx.add(transferIx);
    tx.recentBlockhash = blockhash;
    tx.feePayer = ownerPubkey;

    const serialized = tx
      .serialize({ requireAllSignatures: false })
      .toString("base64");

    // Store seal wallet address in user record
    await db.update(users)
      .set({ sealWalletAddress: walletPda.toBase58() })
      .where(eq(users.walletAddress, ownerAddress));

    return c.json({
      success: true,
      walletAddress: walletPda.toBase58(),
      transaction: serialized,
      sponsored: false,
      depositSol: body.depositSol,
      network: config.SOLANA_NETWORK,
      blockhash,
      lastValidBlockHeight,
    });
  }
);

/**
 * POST /wallet/prepare-deposit
 * Prepare an unsigned SystemProgram.transfer TX to fund an existing
 * Seal wallet with additional SOL.
 */
wallet.post(
  "/prepare-deposit",
  requireAuth,
  zValidator("json", depositSchema),
  async (c) => {
    const userId = c.var.userId;
    const ownerAddress = c.var.walletAddress;
    const body = c.req.valid("json");
    const ownerPubkey = new PublicKey(ownerAddress);

    const walletPda = await getCanonicalWalletPda(userId, ownerPubkey);

    // Verify wallet exists
    const connection = getConnection();
    const existing = await withRpcRetry(() =>
      connection.getAccountInfo(walletPda)
    );
    if (!existing) {
      throw createApiError(
        "Seal wallet not found. Create one first.",
        404
      );
    }

    const depositLamports = BigInt(
      Math.floor(body.amountSol * LAMPORTS_PER_SOL)
    );

    // ── Deposit goes to wallet PDA ──
    // Funds are always deposited to the Seal wallet PDA (the user's
    // non-custodial smart wallet). Before opening trades, the backend
    // uses the Seal program's TransferLamports instruction to pre-fund
    // the session signer from the wallet PDA on-demand.
    const depositTarget = walletPda;
    const depositTargetLabel = "wallet_pda";

    const transferIx = SystemProgram.transfer({
      fromPubkey: ownerPubkey,
      toPubkey: depositTarget,
      lamports: depositLamports,
    });

    const { blockhash, lastValidBlockHeight } =
      await withRpcRetry(() => connection.getLatestBlockhash());

    const tx = new Transaction();
    tx.add(transferIx);

    tx.recentBlockhash = blockhash;
    tx.feePayer = ownerPubkey;

    const serialized = tx
      .serialize({ requireAllSignatures: false })
      .toString("base64");

    return c.json({
      success: true,
      walletAddress: walletPda.toBase58(),
      transaction: serialized,
      depositSol: body.amountSol,
      depositTarget: depositTargetLabel,
      blockhash,
      lastValidBlockHeight,
    });
  }
);

/**
 * GET /wallet/sponsor-status
 * Always returns sponsored: false. Sponsor wallet removed.
 */
wallet.get("/sponsor-status", requireAuth, async (c) => {
  return c.json({
    success: true,
    sponsored: false,
    sponsor: null,
    strategy: null,
  });
});

// ═══════════════════════════════════════════════════════════════
// Per-Bot Agent Registration
// ═══════════════════════════════════════════════════════════════

/** Encode a string as fixed-length bytes (zero-padded) — matches seal-ts */
function encodeFixedString(str: string, length: number): Buffer {
  const buf = Buffer.alloc(length);
  buf.write(str, "utf-8");
  return buf;
}

/** Encode an i64 as little-endian 8 bytes */
function encodeI64(value: bigint): Buffer {
  const buf = Buffer.alloc(8);
  buf.writeBigInt64LE(value);
  return buf;
}

const MAX_AGENT_NAME_LENGTH = 32;

/**
 * Build a RegisterAgent instruction (discriminant = 1).
 *
 * Binary layout:
 *   [0]       disc (1)
 *   [1]       bump
 *   [2..33]   agent pubkey (32 bytes)
 *   [34..65]  name (32 bytes, zero-padded)
 *   [66]      allowedPrograms count
 *   [67..]    allowedPrograms (32 bytes each)
 *   [N]       allowedInstructions count
 *   [N+1..]   allowedInstructions (8 bytes each)
 *   [..]      dailyLimit (u64le)
 *   [..]      perTxLimit (u64le)
 *   [..]      defaultSessionDuration (i64le)
 *   [..]      maxSessionDuration (i64le)
 */
function buildRegisterAgentIx(
  owner: PublicKey,
  walletPda: PublicKey,
  agentPubkey: PublicKey,
  agentPda: PublicKey,
  bump: number,
  name: string,
  dailyLimitLamports: bigint,
  perTxLimitLamports: bigint,
  allowedPrograms: PublicKey[] = [],
  allowedInstructions: Buffer[] = []
) {
  // Defaults matching seal-ts
  const defaultSessionDuration = BigInt(24 * 60 * 60); // 24 hours
  const maxSessionDuration = BigInt(7 * 24 * 60 * 60); // 7 days

  const data = Buffer.concat([
    Buffer.from([1]), // InstructionDiscriminant.RegisterAgent
    Buffer.from([bump]),
    agentPubkey.toBuffer(),
    encodeFixedString(name, MAX_AGENT_NAME_LENGTH),
    Buffer.from([allowedPrograms.length]),
    ...allowedPrograms.map((programId) => programId.toBuffer()),
    Buffer.from([allowedInstructions.length]),
    ...allowedInstructions,
    encodeU64(dailyLimitLamports),
    encodeU64(perTxLimitLamports),
    encodeI64(defaultSessionDuration),
    encodeI64(maxSessionDuration),
  ]);

  return {
    programId: SEAL_PROGRAM_ID,
    keys: [
      { pubkey: owner, isSigner: true, isWritable: true },
      { pubkey: walletPda, isSigner: false, isWritable: true },
      { pubkey: agentPda, isSigner: false, isWritable: true },
      {
        pubkey: SystemProgram.programId,
        isSigner: false,
        isWritable: false,
      },
    ],
    data,
  };
}

/**
 * Build a CreateSession instruction (discriminant = 2).
 *
 * On-chain layout (57 bytes):
 *   [0]       disc (2)
 *   [1]       bump
 *   [2..33]   session_pubkey (32 bytes)
 *   [34..41]  duration_secs (i64 LE)
 *   [42..49]  max_amount_lamports (u64 LE)
 *   [50..57]  max_per_tx_lamports (u64 LE)
 *
 * Accounts (matching seal program create_session.rs):
 *   0. [signer, writable] Agent
 *   1. []                 SmartWallet PDA
 *   2. []                 AgentConfig PDA
 *   3. [writable]         SessionKey PDA
 *   4. []                 System Program
 */
function buildCreateSessionIx(
  agentPubkey: PublicKey,
  walletPda: PublicKey,
  agentPda: PublicKey,
  sessionPda: PublicKey,
  bump: number,
  sessionPubkey: PublicKey,
  durationSecs: bigint,
  maxAmountLamports: bigint,
  maxPerTxLamports: bigint
) {
  const data = Buffer.concat([
    Buffer.from([2]), // InstructionDiscriminant.CreateSessionKey
    Buffer.from([bump]),
    sessionPubkey.toBuffer(),
    encodeI64(durationSecs),
    encodeU64(maxAmountLamports),
    encodeU64(maxPerTxLamports),
  ]);

  return {
    programId: SEAL_PROGRAM_ID,
    keys: [
      { pubkey: agentPubkey, isSigner: true, isWritable: true },
      { pubkey: walletPda, isSigner: false, isWritable: false },
      { pubkey: agentPda, isSigner: false, isWritable: false },
      { pubkey: sessionPda, isSigner: false, isWritable: true },
      {
        pubkey: SystemProgram.programId,
        isSigner: false,
        isWritable: false,
      },
    ],
    data,
  };
}

async function finalizeLiveSession(opts: {
  botId: string;
  userId: number;
  walletPda: PublicKey;
  durationSecs: number;
  maxAmountSol: number;
  maxPerTxSol: number;
}): Promise<{
  sessionAddress: string;
  sessionPubkey: string;
  signature: string;
}> {
  const connection = getConnection();

  const [bot] = await db
    .select()
    .from(bots)
    .where(and(eq(bots.botId, opts.botId), eq(bots.userId, opts.userId)));

  if (!bot?.agentPubkey || !bot.agentSecretKey || !bot.sessionPubkey || !bot.sessionSecretKey) {
    throw createApiError("Live setup keys are missing. Retry setup.", 409);
  }

  const agentPubkey = new PublicKey(bot.agentPubkey);
  const sessionPubkey = new PublicKey(bot.sessionPubkey);
  const agentKeypair = Keypair.fromSecretKey(
    Buffer.from(bot.agentSecretKey, "base64")
  );
  const sessionKeypair = Keypair.fromSecretKey(
    Buffer.from(bot.sessionSecretKey, "base64")
  );

  const [agentPda] = deriveAgentPda(opts.walletPda, agentPubkey);
  const [sessionPda, sessionBump] = deriveSessionPda(
    opts.walletPda,
    agentPubkey,
    sessionPubkey
  );

  const [agentAccount, sessionAccount] = await Promise.all([
    withRpcRetry(() => connection.getAccountInfo(agentPda)),
    withRpcRetry(() => connection.getAccountInfo(sessionPda)),
  ]);

  if (!agentAccount) {
    throw createApiError(
      "Live setup is incomplete. Owner approval did not register the wallet signer.",
      409
    );
  }

  if (sessionAccount) {
    return {
      sessionAddress: sessionPda.toBase58(),
      sessionPubkey: sessionPubkey.toBase58(),
      signature: "already-created",
    };
  }

  const createSessionIx = buildCreateSessionIx(
    agentPubkey,
    opts.walletPda,
    agentPda,
    sessionPda,
    sessionBump,
    sessionPubkey,
    BigInt(opts.durationSecs),
    BigInt(Math.floor(opts.maxAmountSol * LAMPORTS_PER_SOL)),
    BigInt(Math.floor(opts.maxPerTxSol * LAMPORTS_PER_SOL))
  );

  const sessionRentLamports = await withRpcRetry(() =>
    connection.getMinimumBalanceForRentExemption(154) // SessionKey::SIZE
  );
  const signerRentLamports = await withRpcRetry(() =>
    connection.getMinimumBalanceForRentExemption(0)
  );
  const requiredAgentLamports = sessionRentLamports + signerRentLamports + 500_000;
  const agentBalanceLamports = await withRpcRetry(() =>
    connection.getBalance(agentPubkey)
  );

  const tx = new Transaction();
  tx.feePayer = sessionKeypair.publicKey;

  if (agentBalanceLamports < requiredAgentLamports) {
    tx.add(SystemProgram.transfer({
      fromPubkey: sessionKeypair.publicKey,
      toPubkey: agentPubkey,
      lamports: requiredAgentLamports - agentBalanceLamports,
    }));
  }

  tx.add(createSessionIx);

  const txSender = new TransactionSender(connection);
  const txWithFees = txSender.addPriorityFee(tx);
  const result = await txSender.sendTransaction(txWithFees, [sessionKeypair, agentKeypair]);

  if (!result.success || !result.signature) {
    throw createApiError(
      `Failed to finalize live setup: ${result.error ?? "unknown error"}`,
      500
    );
  }

  await db.update(bots)
    .set({
      agentConfigAddress: agentPda.toBase58(),
      sessionAddress: sessionPda.toBase58(),
      updatedAt: new Date(),
    })
    .where(eq(bots.botId, opts.botId));

  return {
    sessionAddress: sessionPda.toBase58(),
    sessionPubkey: sessionPubkey.toBase58(),
    signature: result.signature,
  };
}

/**
 * Build a RevokeSession instruction (discriminant = 4).
 *
 * On-chain layout (1 byte):
 *   [0]  disc (4)
 *
 * Accounts (matching seal program revoke_session.rs):
 *   0. [signer]    Authority (wallet owner OR agent)
 *   1. [writable]  SessionKey PDA
 *   2. []          SmartWallet PDA
 */
function buildRevokeSessionIx(
  authority: PublicKey,
  sessionPda: PublicKey,
  walletPda: PublicKey
) {
  const data = Buffer.from([4]); // InstructionDiscriminant.RevokeSession

  return {
    programId: SEAL_PROGRAM_ID,
    keys: [
      { pubkey: authority, isSigner: true, isWritable: false },
      { pubkey: sessionPda, isSigner: false, isWritable: true },
      { pubkey: walletPda, isSigner: false, isWritable: false },
    ],
    data,
  };
}

function buildDeregisterAgentIx(
  owner: PublicKey,
  walletPda: PublicKey,
  agentPda: PublicKey
) {
  return {
    programId: SEAL_PROGRAM_ID,
    keys: [
      { pubkey: owner, isSigner: true, isWritable: true },
      { pubkey: walletPda, isSigner: false, isWritable: true },
      { pubkey: agentPda, isSigner: false, isWritable: true },
    ],
    data: Buffer.from([8]), // DeregisterAgent
  };
}

function buildCloseWalletIx(owner: PublicKey, walletPda: PublicKey) {
  return {
    programId: SEAL_PROGRAM_ID,
    keys: [
      { pubkey: owner, isSigner: true, isWritable: true },
      { pubkey: walletPda, isSigner: false, isWritable: true },
    ],
    data: Buffer.from([9]), // CloseWallet
  };
}

/**
 * POST /wallet/prepare-register-agent
 * Prepare TX to register a bot as a Seal agent on the user's wallet.
 *
 * Flow:
 * 1. Validate the bot exists, belongs to the user, and is live mode
 * 2. Derive the AgentConfig PDA
 * 3. Build the RegisterAgent instruction
 * 4. Return serialized TX for MWA signing
 * 5. Store agentPubkey + agentConfigAddress in the bot row
 */
wallet.post(
  "/prepare-register-agent",
  requireAuth,
  zValidator("json", registerAgentSchema),
  async (c) => {
    const userId = c.var.userId;
    const ownerAddress = c.var.walletAddress;
    const body = c.req.valid("json");

    const ownerPubkey = new PublicKey(ownerAddress);
    const agentPubkey = new PublicKey(body.agentPubkey);
    const allowedPrograms = resolveAgentAllowedPrograms(body.allowedPrograms);

    // ── Validate bot ──
    const [bot] = await db
      .select()
      .from(bots)
      .where(and(eq(bots.botId, body.botId), eq(bots.userId, userId)));

    if (!bot) {
      throw createApiError("Bot not found", 404);
    }

    if (bot.mode !== "live") {
      throw createApiError(
        "Agent registration is only required for live-mode bots",
        400
      );
    }

    if (bot.agentPubkey) {
      throw createApiError("Bot already has an agent registered", 409, {
        agentPubkey: bot.agentPubkey,
        agentConfigAddress: bot.agentConfigAddress,
      });
    }

    // ── Verify Seal wallet exists ──
    const walletPda = await getCanonicalWalletPda(userId, ownerPubkey);
    const connection = getConnection();
    const walletAccount = await withRpcRetry(() =>
      connection.getAccountInfo(walletPda)
    );
    if (!walletAccount) {
      throw createApiError(
        "Seal wallet not found. Create one first.",
        404
      );
    }

    // ── Derive agent PDA ──
    const [agentPda, bump] = deriveAgentPda(walletPda, agentPubkey);

    // Check if agent PDA already exists on-chain
    const existingAgent = await withRpcRetry(() =>
      connection.getAccountInfo(agentPda)
    );
    if (existingAgent) {
      throw createApiError("Agent account already exists on-chain", 409, {
        agentConfigAddress: agentPda.toBase58(),
      });
    }

    // ── Build TX ──
    const dailyLimitLamports = BigInt(
      Math.floor(body.dailyLimitSol * LAMPORTS_PER_SOL)
    );
    const perTxLimitLamports = BigInt(
      Math.floor(body.perTxLimitSol * LAMPORTS_PER_SOL)
    );

    const sponsored = false;
    const funderPubkey = ownerPubkey;

    const ix = buildRegisterAgentIx(
      ownerPubkey,
      walletPda,
      agentPubkey,
      agentPda,
      bump,
      body.name,
      dailyLimitLamports,
      perTxLimitLamports,
      allowedPrograms
    );

    const { blockhash, lastValidBlockHeight } = await withRpcRetry(() =>
      connection.getLatestBlockhash()
    );

    const tx = new Transaction();
    tx.add(ix);
    tx.recentBlockhash = blockhash;
    tx.feePayer = funderPubkey;

    const serialized = tx
      .serialize({ requireAllSignatures: false })
      .toString("base64");

    // ── Persist agent info in bot row ──
    await db.update(bots)
      .set({
        agentPubkey: agentPubkey.toBase58(),
        agentConfigAddress: agentPda.toBase58(),
        updatedAt: new Date(),
      })
      .where(eq(bots.botId, body.botId));

    return c.json({
      success: true,
      botId: body.botId,
      agentPubkey: agentPubkey.toBase58(),
      agentConfigAddress: agentPda.toBase58(),
      allowedPrograms: allowedPrograms.map((programId) => programId.toBase58()),
      transaction: serialized,
      sponsored,
      network: config.SOLANA_NETWORK,
      blockhash,
      lastValidBlockHeight,
    });
  }
);

// ═══════════════════════════════════════════════════════════════
// Session Key Management
// ═══════════════════════════════════════════════════════════════

/**
 * POST /wallet/prepare-create-session
 * Prepare TX to create a session key for an agent.
 *
 * The agent (bot keypair) is the signer/payer for session creation on-chain.
 * However, since the Flutter app signs via MWA (owner wallet), we prepare
 * the TX for the OWNER to sign — the agent keypair is stored server-side
 * and we don't require it to sign here. The Flutter app must ensure the
 * agent keypair also signs before submission.
 *
 * Flow:
 * 1. Validate bot exists, belongs to user, and has a registered agent
 * 2. Verify the bot doesn't already have an active session
 * 3. Derive the SessionKey PDA from (walletPda, agentPubkey, sessionPubkey)
 * 4. Build CreateSession instruction
 * 5. Return serialized TX for client-side signing (agent signs)
 * 6. Store sessionAddress in bot row
 */
wallet.post(
  "/prepare-create-session",
  requireAuth,
  zValidator("json", createSessionSchema),
  async (c) => {
    const userId = c.var.userId;
    const ownerAddress = c.var.walletAddress;
    const body = c.req.valid("json");

    const ownerPubkey = new PublicKey(ownerAddress);
    const sessionPubkey = new PublicKey(body.sessionPubkey);

    // ── Validate bot ──
    const [bot] = await db
      .select()
      .from(bots)
      .where(and(eq(bots.botId, body.botId), eq(bots.userId, userId)));

    if (!bot) {
      throw createApiError("Bot not found", 404);
    }

    if (bot.mode !== "live") {
      throw createApiError(
        "Session keys are only used for live-mode bots",
        400
      );
    }

    if (!bot.agentPubkey || !bot.agentConfigAddress) {
      throw createApiError(
        "Bot must have a registered agent before creating a session. " +
        "Use /wallet/prepare-register-agent first.",
        400
      );
    }

    if (bot.sessionAddress) {
      throw createApiError("Bot already has an active session", 409, {
        sessionAddress: bot.sessionAddress,
      });
    }

    // ── Verify Seal wallet exists on-chain ──
    const walletPda = await getCanonicalWalletPda(userId, ownerPubkey);
    const connection = getConnection();
    const walletAccount = await withRpcRetry(() =>
      connection.getAccountInfo(walletPda)
    );
    if (!walletAccount) {
      throw createApiError(
        "Seal wallet not found. Create one first.",
        404
      );
    }

    // ── Derive PDAs ──
    const agentPubkey = new PublicKey(bot.agentPubkey);
    const [agentPda] = deriveAgentPda(walletPda, agentPubkey);

    // Verify agent config exists on-chain
    const agentAccount = await withRpcRetry(() =>
      connection.getAccountInfo(agentPda)
    );
    if (!agentAccount) {
      throw createApiError(
        "Agent config not found on-chain. Register the agent first.",
        404,
        { expectedAddress: agentPda.toBase58() }
      );
    }

    const [sessionPda, bump] = deriveSessionPda(
      walletPda,
      agentPubkey,
      sessionPubkey
    );

    // Verify session PDA doesn't already exist on-chain
    const existingSession = await withRpcRetry(() =>
      connection.getAccountInfo(sessionPda)
    );
    if (existingSession) {
      throw createApiError("Session account already exists on-chain", 409, {
        sessionAddress: sessionPda.toBase58(),
      });
    }

    // ── Build TX ──
    const durationSecs = BigInt(body.durationSecs);
    const maxAmountLamports = BigInt(
      Math.floor(body.maxAmountSol * LAMPORTS_PER_SOL)
    );
    const maxPerTxLamports = BigInt(
      Math.floor(body.maxPerTxSol * LAMPORTS_PER_SOL)
    );

    // Validate spending limits: session limits should not exceed what
    // was set at agent registration level
    if (maxPerTxLamports > maxAmountLamports) {
      throw createApiError(
        "maxPerTxSol cannot exceed maxAmountSol",
        400
      );
    }

    const ix = buildCreateSessionIx(
      agentPubkey,  // agent is signer/payer on-chain
      walletPda,
      agentPda,
      sessionPda,
      bump,
      sessionPubkey,
      durationSecs,
      maxAmountLamports,
      maxPerTxLamports
    );

    const { blockhash, lastValidBlockHeight } = await withRpcRetry(() =>
      connection.getLatestBlockhash()
    );

    const tx = new Transaction();
    tx.add(ix);
    tx.recentBlockhash = blockhash;
    // Agent is the fee payer for session creation (they're the signer on-chain)
    tx.feePayer = agentPubkey;

    const serialized = tx
      .serialize({ requireAllSignatures: false })
      .toString("base64");

    // ── Persist session info in bot row ──
    await db.update(bots)
      .set({
        sessionAddress: sessionPda.toBase58(),
        updatedAt: new Date(),
      })
      .where(eq(bots.botId, body.botId));

    return c.json({
      success: true,
      botId: body.botId,
      sessionAddress: sessionPda.toBase58(),
      sessionPubkey: sessionPubkey.toBase58(),
      agentPubkey: bot.agentPubkey,
      durationSecs: body.durationSecs,
      maxAmountSol: body.maxAmountSol,
      maxPerTxSol: body.maxPerTxSol,
      transaction: serialized,
      blockhash,
      lastValidBlockHeight,
    });
  }
);

// ═══════════════════════════════════════════════════════════════
// Combined Live Setup (Agent + Session in one TX)
// ═══════════════════════════════════════════════════════════════

const setupLiveSchema = z.object({
  botId: z.string(),
  /** Agent spending limits */
  dailyLimitSol: z.number().positive().max(1000).default(10),
  perTxLimitSol: z.number().positive().max(100).default(2),
  /** Trading capital — goes directly to session signer */
  depositSol: z.number().nonnegative().max(1000).default(0),
  /** Session config */
  sessionDurationSecs: z.number().int().positive().default(7 * 24 * 60 * 60), // 7 days
  sessionMaxAmountSol: z.number().positive().default(100),
  sessionMaxPerTxSol: z.number().positive().default(2),
  allowedPrograms: z.array(z.string().min(32).max(50)).max(16).optional(),
});

/**
 * POST /wallet/setup-live
 * Prepare the owner-signed phase of live setup.
 *
 * The wallet-facing transaction is owner-only:
 * 1. fund agent signer
 * 2. fund session signer
 * 3. register agent
 *
 * After the owner-signed transaction is submitted, the backend finalizes
 * `CreateSession` separately using the stored agent keypair.
 */
wallet.post(
  "/setup-live",
  requireAuth,
  zValidator("json", setupLiveSchema),
  async (c) => {
    const userId = c.var.userId;
    const ownerAddress = c.var.walletAddress;
    const body = c.req.valid("json");

    const ownerPubkey = new PublicKey(ownerAddress);
    const allowedPrograms = resolveAgentAllowedPrograms(body.allowedPrograms);
    const effectiveSessionMaxAmountSol = Math.min(
      body.sessionMaxAmountSol,
      body.dailyLimitSol,
    );
    const effectiveSessionMaxPerTxSol = Math.min(
      body.sessionMaxPerTxSol,
      body.perTxLimitSol,
    );

    // ── Validate bot ──
    const [bot] = await db
      .select()
      .from(bots)
      .where(and(eq(bots.botId, body.botId), eq(bots.userId, userId)));

    if (!bot) {
      throw createApiError("Bot not found", 404);
    }

    if (bot.mode !== "live") {
      throw createApiError(
        "Live setup is only for live-mode bots",
        400
      );
    }

    // ── Derive wallet PDA & check if it exists on-chain ──
    // If wallet doesn't exist, we create it in the SAME transaction
    // to avoid requiring a separate MWA signature.
    const [walletPda, walletBump] = deriveWalletPda(ownerPubkey);
    const connection = getConnection();
    const walletAccount = await withRpcRetry(() =>
      connection.getAccountInfo(walletPda)
    );
    const needsWalletCreation = !walletAccount;

    // Store wallet address in DB if not already set
    const [currentUser] = await db
      .select({ sealWalletAddress: users.sealWalletAddress })
      .from(users)
      .where(eq(users.id, userId));
    if (!currentUser?.sealWalletAddress) {
      await db.update(users)
        .set({ sealWalletAddress: walletPda.toBase58() })
        .where(eq(users.id, userId));
    }

    // ── Calculate session funding ──
    // The session signer pays for ALL on-chain costs: position rent,
    // ATA creation, SOL wrapping, TX fees. The user's deposit goes
    // directly here — no separate deposit step needed.
    const POSITION_RENT_ESTIMATE = 60_000_000;  // 0.06 SOL
    const TX_FEE_BUFFER = 10_000_000;           // 0.01 SOL
    const FINALIZATION_BUFFER = 5_000_000;       // 0.005 SOL (CreateSession TX fee)
    const positionLamports = Math.floor(body.perTxLimitSol * LAMPORTS_PER_SOL);
    const minSessionFunding = positionLamports + POSITION_RENT_ESTIMATE + TX_FEE_BUFFER + FINALIZATION_BUFFER;
    const depositLamports = body.depositSol > 0
      ? Math.floor(body.depositSol * LAMPORTS_PER_SOL)
      : minSessionFunding;

    if (depositLamports < minSessionFunding) {
      const minSol = (minSessionFunding / LAMPORTS_PER_SOL).toFixed(3);
      throw createApiError(
        `Minimum deposit is ${minSol} SOL for a ${body.perTxLimitSol} SOL position size (covers rent + fees).`,
        400
      );
    }

    // ── Handle retry: keys in DB but TX was never signed (user cancelled MWA) ──
    let agentKeypair: Keypair;
    let sessionKeypair: Keypair;

    if (bot.agentPubkey && bot.sessionAddress && bot.agentSecretKey && bot.sessionSecretKey) {
      // Keys exist in DB — check if accounts exist on-chain
      const existingAgentPubkey = new PublicKey(bot.agentPubkey);
      const existingSessionPubkey = new PublicKey(bot.sessionPubkey!);
      const [existingAgentPda] = deriveAgentPda(walletPda, existingAgentPubkey);
      const [existingSessionPda] = deriveSessionPda(walletPda, existingAgentPubkey, existingSessionPubkey);

      const [onChainAgent, onChainSession] = await Promise.all([
        withRpcRetry(() => connection.getAccountInfo(existingAgentPda)),
        withRpcRetry(() => connection.getAccountInfo(existingSessionPda)),
      ]);

      if (onChainAgent && onChainSession) {
        // Both exist on-chain — setup truly complete, this is a real 409
        throw createApiError("Bot already has agent + session configured and confirmed on-chain", 409, {
          agentPubkey: bot.agentPubkey,
          sessionAddress: bot.sessionAddress,
        });
      }

      if (onChainAgent && !onChainSession) {
        const finalized = await finalizeLiveSession({
          botId: body.botId,
          userId,
          walletPda,
          durationSecs: body.sessionDurationSecs,
          maxAmountSol: effectiveSessionMaxAmountSol,
          maxPerTxSol: effectiveSessionMaxPerTxSol,
        });

        return c.json({
          success: true,
          botId: body.botId,
          agentPubkey: bot.agentPubkey,
          agentConfigAddress: bot.agentConfigAddress,
          sessionAddress: finalized.sessionAddress,
          sessionPubkey: finalized.sessionPubkey,
          finalized: true,
          finalizeSignature: finalized.signature,
          network: config.SOLANA_NETWORK,
        });
      }

      // Accounts NOT on-chain — user cancelled MWA. Reconstruct keypairs
      // from stored secrets and rebuild TX so they can sign again.
      console.log(
        `[setup-live] Bot ${body.botId}: keys in DB but not on-chain — rebuilding TX for retry`
      );
      agentKeypair = Keypair.fromSecretKey(
        Buffer.from(bot.agentSecretKey, "base64")
      );
      sessionKeypair = Keypair.fromSecretKey(
        Buffer.from(bot.sessionSecretKey, "base64")
      );
    } else {
      // ── Generate fresh keypairs server-side ──
      agentKeypair = Keypair.generate();
      sessionKeypair = Keypair.generate();
    }

    // ── Derive PDAs ──
    const [agentPda, agentBump] = deriveAgentPda(walletPda, agentKeypair.publicKey);
    const [sessionPda] = deriveSessionPda(
      walletPda,
      agentKeypair.publicKey,
      sessionKeypair.publicKey
    );

    // Verify neither PDA exists on-chain (safety check for fresh keys too)
    const [existingAgent, existingSession] = await Promise.all([
      withRpcRetry(() => connection.getAccountInfo(agentPda)),
      withRpcRetry(() => connection.getAccountInfo(sessionPda)),
    ]);
    if (existingAgent && existingSession) {
      throw createApiError("Agent + session accounts already exist on-chain", 409);
    }

    if (existingAgent && !existingSession) {
      const finalized = await finalizeLiveSession({
        botId: body.botId,
        userId,
        walletPda,
        durationSecs: body.sessionDurationSecs,
        maxAmountSol: effectiveSessionMaxAmountSol,
        maxPerTxSol: effectiveSessionMaxPerTxSol,
      });

      return c.json({
        success: true,
        botId: body.botId,
        agentPubkey: agentKeypair.publicKey.toBase58(),
        agentConfigAddress: agentPda.toBase58(),
        sessionAddress: finalized.sessionAddress,
        sessionPubkey: finalized.sessionPubkey,
        finalized: true,
        finalizeSignature: finalized.signature,
        network: config.SOLANA_NETWORK,
      });
    }

    // ── Build RegisterAgent IX ──
    const dailyLimitLamports = BigInt(
      Math.floor(body.dailyLimitSol * LAMPORTS_PER_SOL)
    );
    const perTxLimitLamports = BigInt(
      Math.floor(body.perTxLimitSol * LAMPORTS_PER_SOL)
    );

    const registerIx = buildRegisterAgentIx(
      ownerPubkey,
      walletPda,
      agentKeypair.publicKey,
      agentPda,
      agentBump,
      `bot-${body.botId}`,
      dailyLimitLamports,
      perTxLimitLamports,
      allowedPrograms
    );

    // ── Assemble TX ──
    const { blockhash, lastValidBlockHeight } = await withRpcRetry(() =>
      connection.getLatestBlockhash()
    );
    const funderPubkey = ownerPubkey;

    const tx = new Transaction();

    // 0. Create wallet PDA if it doesn't exist (avoids separate MWA signature)
    if (needsWalletCreation) {
      tx.add(buildCreateWalletIx(
        funderPubkey,
        ownerPubkey,
        walletPda,
        walletBump,
        dailyLimitLamports,
        perTxLimitLamports
      ));
    }

    // 1. Fund agent so it can pay SessionKey PDA rent during finalization
    const sessionRentLamports = await withRpcRetry(() =>
      connection.getMinimumBalanceForRentExemption(154) // SessionKey::SIZE
    );
    const signerRentLamports = await withRpcRetry(() =>
      connection.getMinimumBalanceForRentExemption(0)
    );
    const agentFundingLamports = sessionRentLamports + signerRentLamports + 500_000;

    tx.add(SystemProgram.transfer({
      fromPubkey: funderPubkey,
      toPubkey: agentKeypair.publicKey,
      lamports: agentFundingLamports,
    }));

    // 2. Fund session signer with user's deposit (trading capital)
    // This is the ONLY place the user's deposit goes — directly to the
    // session signer that actually pays for trading operations.
    tx.add(SystemProgram.transfer({
      fromPubkey: funderPubkey,
      toPubkey: sessionKeypair.publicKey,
      lamports: depositLamports,
    }));

    // 3. Register agent on the Seal wallet
    tx.add(registerIx);

    tx.recentBlockhash = blockhash;
    tx.feePayer = funderPubkey;

    const serialized = tx
      .serialize({ requireAllSignatures: false, verifySignatures: false })
      .toString("base64");

    // Total user cost breakdown for transparency
    const totalUserCostLamports = agentFundingLamports + depositLamports
      + (needsWalletCreation ? 2_900_000 : 0); // ~0.0029 SOL wallet PDA rent estimate
    const totalUserCostSol = totalUserCostLamports / LAMPORTS_PER_SOL;
    const sessionFundingSol = depositLamports / LAMPORTS_PER_SOL;

    // ── Persist keys in DB ──
    // Store private keys as base64-encoded Uint8Array (64 bytes: seed + pubkey)
    await db.update(bots)
      .set({
        agentPubkey: agentKeypair.publicKey.toBase58(),
        agentSecretKey: Buffer.from(agentKeypair.secretKey).toString("base64"),
        agentConfigAddress: agentPda.toBase58(),
        sessionAddress: sessionPda.toBase58(),
        sessionPubkey: sessionKeypair.publicKey.toBase58(),
        sessionSecretKey: Buffer.from(sessionKeypair.secretKey).toString("base64"),
        updatedAt: new Date(),
      })
      .where(eq(bots.botId, body.botId));

    return c.json({
      success: true,
      botId: body.botId,
      agentPubkey: agentKeypair.publicKey.toBase58(),
      agentConfigAddress: agentPda.toBase58(),
      sessionAddress: sessionPda.toBase58(),
      sessionPubkey: sessionKeypair.publicKey.toBase58(),
      allowedPrograms: allowedPrograms.map((programId) => programId.toBase58()),
      effectiveSessionMaxAmountSol,
      effectiveSessionMaxPerTxSol,
      walletCreated: needsWalletCreation,
      walletAddress: walletPda.toBase58(),
      sessionFundingSol,
      totalCostSol: totalUserCostSol,
      transaction: serialized,
      requiresOwnerSignature: true,
      network: config.SOLANA_NETWORK,
      blockhash,
      lastValidBlockHeight,
    });
  }
);

/**
 * POST /wallet/prepare-revoke-session
 * Prepare TX to revoke an active session key.
 *
 * Either the wallet owner or the agent can revoke a session.
 * This endpoint prepares the TX for the owner to sign via MWA.
 *
 * Flow:
 * 1. Validate bot exists, belongs to user, and has an active session
 * 2. Load the on-chain session account to extract agent + sessionPubkey
 * 3. Build RevokeSession instruction (owner as authority)
 * 4. Return serialized TX for MWA signing
 * 5. Clear sessionAddress from bot row
 */
wallet.post(
  "/prepare-revoke-session",
  requireAuth,
  zValidator("json", revokeSessionSchema),
  async (c) => {
    const userId = c.var.userId;
    const ownerAddress = c.var.walletAddress;
    const body = c.req.valid("json");

    const ownerPubkey = new PublicKey(ownerAddress);

    // ── Validate bot ──
    const [bot] = await db
      .select()
      .from(bots)
      .where(and(eq(bots.botId, body.botId), eq(bots.userId, userId)));

    if (!bot) {
      throw createApiError("Bot not found", 404);
    }

    if (!bot.sessionAddress) {
      throw createApiError("Bot has no active session to revoke", 400);
    }

    // ── Verify session account exists on-chain ──
    const sessionPda = new PublicKey(bot.sessionAddress);
    const connection = getConnection();
    const sessionAccount = await withRpcRetry(() =>
      connection.getAccountInfo(sessionPda)
    );

    if (!sessionAccount) {
      // Session doesn't exist on-chain — clean up DB and return success
      await db.update(bots)
        .set({
          sessionAddress: null,
          updatedAt: new Date(),
        })
        .where(eq(bots.botId, body.botId));

      return c.json({
        success: true,
        botId: body.botId,
        message: "Session already closed on-chain. Database cleaned up.",
        alreadyClosed: true,
      });
    }

    // Parse session to check if already revoked
    const sessionData = sessionAccount.data as Buffer;
    if (sessionData.length < 154) {
      throw createApiError("Invalid session account data", 500);
    }

    const isRevoked = sessionData[145] !== 0; // offset: 8(disc)+32(wallet)+32(agent)+32(session)+1(bump)+8(created)+8(expires)+8(max)+8(spent)+8(perTx) = 145
    if (isRevoked) {
      // Already revoked on-chain — clean up DB
      await db.update(bots)
        .set({
          sessionAddress: null,
          updatedAt: new Date(),
        })
        .where(eq(bots.botId, body.botId));

      return c.json({
        success: true,
        botId: body.botId,
        message: "Session was already revoked on-chain. Database cleaned up.",
        alreadyRevoked: true,
      });
    }

    // ── Build TX ──
    const walletPda = await getCanonicalWalletPda(userId, ownerPubkey);

    const ix = buildRevokeSessionIx(
      ownerPubkey, // owner as authority
      sessionPda,
      walletPda
    );

    const { blockhash, lastValidBlockHeight } = await withRpcRetry(() =>
      connection.getLatestBlockhash()
    );

    const tx = new Transaction();
    tx.add(ix);
    tx.recentBlockhash = blockhash;
    tx.feePayer = ownerPubkey;

    const serialized = tx
      .serialize({ requireAllSignatures: false })
      .toString("base64");

    // ── Clear session from bot row ──
    await db.update(bots)
      .set({
        sessionAddress: null,
        updatedAt: new Date(),
      })
      .where(eq(bots.botId, body.botId));

    return c.json({
      success: true,
      botId: body.botId,
      sessionAddress: bot.sessionAddress,
      transaction: serialized,
      network: config.SOLANA_NETWORK,
      blockhash,
      lastValidBlockHeight,
    });
  }
);

// ═══════════════════════════════════════════════════════════════
// Withdraw SOL from session signers → owner
// ═══════════════════════════════════════════════════════════════

const withdrawSchema = z.object({
  /** SOL to withdraw. Use 0 or omit to withdraw maximum available. */
  amountSol: z.number().min(0).max(10_000).default(0),
  /** Optional bot IDs to withdraw from. If omitted, drains all. */
  botIds: z.array(z.string()).optional(),
});

const prepareRecoverWalletSchema = z.object({});

// ── NOTE: Direct SOL withdraw via SystemProgram.transfer is IMPOSSIBLE ──
// The Seal wallet PDA is owned by the Seal program, not the System Program.
// SystemProgram.transfer requires the sender account to be owned by
// SystemProgram, so it will always fail with "Provided owner is not allowed".
//
// Use POST /wallet/prepare-recover-wallet instead — this closes the wallet
// via the Seal program's CloseWallet instruction, returning ALL lamports
// to the owner. For partial withdrawals, the Seal program would need a
// dedicated WithdrawFromWallet instruction (future upgrade).

/**
 * POST /wallet/withdraw
 * Withdraw SOL from the Sage smart wallet back to the user's connected wallet.
 *
 * Uses an existing live-bot session keypair to issue a
 * SystemProgram::Transfer via ExecuteViaSession. The backend signs
 * and submits — no MWA interaction needed.
 *
 * If amountSol is 0, withdraws everything except a 0.003 SOL rent buffer.
 */
wallet.post(
  "/prepare-recover-wallet",
  requireAuth,
  zValidator("json", prepareRecoverWalletSchema),
  async (c) => {
    const userId = c.var.userId;
    const ownerAddress = c.var.walletAddress;
    const ownerPubkey = new PublicKey(ownerAddress);
    const walletPda = await getCanonicalWalletPda(userId, ownerPubkey);
    const connection = getConnection();

    const walletAccount = await withRpcRetry(() => connection.getAccountInfo(walletPda));

    const botRows = await db
      .select({
        agentPubkey: bots.agentPubkey,
        sessionPubkey: bots.sessionPubkey,
        sessionSecretKey: bots.sessionSecretKey,
      })
      .from(bots)
      .where(and(eq(bots.userId, userId), eq(bots.mode, "live")));

    const uniqueAgents = [
      ...new Set(
        botRows
          .map((b) => b.agentPubkey)
          .filter((v): v is string => Boolean(v))
      ),
    ];

    const tx = new Transaction();
    tx.feePayer = ownerPubkey;

    // ── Drain all session signers back to owner ──
    // Session signers are System-owned keypairs — we have their secret
    // keys and can sign SystemProgram::Transfer directly.
    // Transfer the FULL balance — the tx fee comes from feePayer (owner),
    // so the session signer can go to 0 lamports (garbage collected).
    const sessionSigners: Keypair[] = [];
    const seen = new Set<string>();
    let sessionSolRecovered = 0;

    for (const bot of botRows) {
      if (!bot.sessionPubkey || !bot.sessionSecretKey || seen.has(bot.sessionPubkey)) continue;
      seen.add(bot.sessionPubkey);
      try {
        const sessionKp = Keypair.fromSecretKey(
          Buffer.from(bot.sessionSecretKey, "base64")
        );
        const balance = await connection.getBalance(sessionKp.publicKey);
        if (balance > 0) {
          tx.add(
            SystemProgram.transfer({
              fromPubkey: sessionKp.publicKey,
              toPubkey: ownerPubkey,
              lamports: balance,
            })
          );
          sessionSigners.push(sessionKp);
          sessionSolRecovered += balance / LAMPORTS_PER_SOL;
        }
      } catch { /* skip invalid keys */ }
    }

    // ── Deregister agents + close wallet (if PDA exists) ──
    if (walletAccount) {
      for (const agentPubkeyStr of uniqueAgents) {
        const agentPubkey = new PublicKey(agentPubkeyStr);
        const [agentPda] = deriveAgentPda(walletPda, agentPubkey);
        const agentAccount = await withRpcRetry(() => connection.getAccountInfo(agentPda));
        if (agentAccount) {
          tx.add(buildDeregisterAgentIx(ownerPubkey, walletPda, agentPda));
        }
      }
      tx.add(buildCloseWalletIx(ownerPubkey, walletPda));
    }

    // If there's nothing to recover at all, error out
    if (tx.instructions.length === 0) {
      throw createApiError(
        "Nothing to recover — no wallet PDA and no session signer funds found.",
        404
      );
    }

    const { blockhash, lastValidBlockHeight } = await withRpcRetry(() =>
      connection.getLatestBlockhash("confirmed")
    );
    tx.recentBlockhash = blockhash;
    tx.lastValidBlockHeight = lastValidBlockHeight;

    // Partially sign with session signers (backend has keys)
    for (const signer of sessionSigners) {
      tx.partialSign(signer);
    }

    return c.json({
      success: true,
      transaction: tx.serialize({
        requireAllSignatures: false,
        verifySignatures: false,
      }).toString("base64"),
      network: config.SOLANA_NETWORK,
      walletAddress: walletPda.toBase58(),
      recoveryClosesWallet: !!walletAccount,
      agentsToRemove: uniqueAgents.length,
      sessionSignersDrained: sessionSigners.length,
      sessionSolRecovered: +sessionSolRecovered.toFixed(6),
      blockhash,
      lastValidBlockHeight,
    });
  }
);

/**
 * POST /wallet/withdraw
 *
 * Smart withdrawal: drain ALL user funds — session signers + wallet PDA.
 *
 * 1. Session signers: drained via SystemProgram.transfer (backend signs)
 * 2. Wallet PDA: drained via DeregisterAgent + CloseWallet (owner signs)
 *
 * - If amountSol is 0, drains everything from all (or specified) bots.
 * - If amountSol > 0, drains that exact amount spread across session
 *   signers first; wallet PDA is only closed when draining everything.
 * - If botIds is provided, only those bots' session signers are touched.
 *
 * One TX, one MWA signature, all funds returned.
 */
wallet.post(
  "/withdraw",
  requireAuth,
  zValidator("json", withdrawSchema),
  async (c) => {
    const userId = c.var.userId;
    const ownerAddress = c.var.walletAddress;
    const ownerPubkey = new PublicKey(ownerAddress);
    const connection = getConnection();
    const body = c.req.valid("json");

    const requestedLamports = Math.floor(body.amountSol * LAMPORTS_PER_SOL);
    const drainAll = requestedLamports === 0;

    // ── Check wallet PDA balance ──
    let walletPdaLamports = 0;
    let walletPda: PublicKey | null = null;
    let walletAccountExists = false;
    try {
      walletPda = await getCanonicalWalletPda(userId, ownerPubkey);
      const walletAccount = await withRpcRetry(() =>
        connection.getAccountInfo(walletPda!)
      );
      walletAccountExists = !!walletAccount;
      if (walletAccountExists) {
        walletPdaLamports = await connection.getBalance(walletPda);
      }
    } catch { /* wallet may not exist */ }

    // ── Fetch ALL session signers (including soft-deleted bots) ──
    const sessionRows = await db
      .select({
        botId: bots.botId,
        sessionPubkey: bots.sessionPubkey,
        sessionSecretKey: bots.sessionSecretKey,
        agentPubkey: bots.agentPubkey,
        name: bots.name,
      })
      .from(bots)
      .where(and(
        eq(bots.userId, userId),
        eq(bots.mode, "live"),
        isNotNull(bots.sessionPubkey),
        isNotNull(bots.sessionSecretKey),
      ));

    // Filter by botIds if specified
    const filtered = body.botIds
      ? sessionRows.filter((r) => body.botIds!.includes(r.botId))
      : sessionRows;

    // Deduplicate by sessionPubkey and get on-chain balances
    const seen = new Set<string>();
    const sources: { kp: Keypair; balance: number; botId: string; name: string | null }[] = [];

    for (const row of filtered) {
      if (!row.sessionPubkey || !row.sessionSecretKey || seen.has(row.sessionPubkey)) continue;
      seen.add(row.sessionPubkey);
      try {
        const kp = Keypair.fromSecretKey(Buffer.from(row.sessionSecretKey, "base64"));
        const balance = await connection.getBalance(kp.publicKey);
        if (balance > 0) {
          sources.push({ kp, balance, botId: row.botId, name: row.name });
        }
      } catch (err: any) {
        console.error(`[withdraw] Failed to check session signer for bot ${row.botId}: ${err?.message ?? err}`);
      }
    }

    const totalSessionLamports = sources.reduce((sum, s) => sum + s.balance, 0);
    const totalAvailable = totalSessionLamports + walletPdaLamports;

    if (totalAvailable === 0) {
      throw createApiError(
        "No funds available to withdraw. All session signers and wallet PDA are at 0 SOL.",
        404
      );
    }

    // Sort largest-balance-first for efficient draining
    sources.sort((a, b) => b.balance - a.balance);

    // Build transaction
    const tx = new Transaction();
    tx.feePayer = ownerPubkey;
    const signers: Keypair[] = [];
    let sessionDrained = 0;
    const drainDetails: { botId: string; name: string | null; lamports: number }[] = [];

    // ── 1. Drain session signers ──
    if (drainAll) {
      // Drain everything from all session signers
      for (const source of sources) {
        tx.add(
          SystemProgram.transfer({
            fromPubkey: source.kp.publicKey,
            toPubkey: ownerPubkey,
            lamports: source.balance,
          })
        );
        signers.push(source.kp);
        drainDetails.push({ botId: source.botId, name: source.name, lamports: source.balance });
        sessionDrained += source.balance;
      }
    } else {
      // Drain up to the requested amount
      let remaining = Math.min(requestedLamports, totalSessionLamports);
      for (const source of sources) {
        if (remaining <= 0) break;
        const take = Math.min(remaining, source.balance);
        tx.add(
          SystemProgram.transfer({
            fromPubkey: source.kp.publicKey,
            toPubkey: ownerPubkey,
            lamports: take,
          })
        );
        signers.push(source.kp);
        drainDetails.push({ botId: source.botId, name: source.name, lamports: take });
        sessionDrained += take;
        remaining -= take;
      }
    }

    // ── 2. Close wallet PDA to recover its SOL ──
    // Only when draining everything AND the wallet PDA exists with balance.
    let closesWallet = false;
    if (drainAll && walletAccountExists && walletPda && walletPdaLamports > 0) {
      // Deregister all agents so CloseWallet can succeed
      const uniqueAgents = [
        ...new Set(
          sessionRows
            .map((b) => b.agentPubkey)
            .filter((v): v is string => Boolean(v))
        ),
      ];
      for (const agentPubkeyStr of uniqueAgents) {
        const agentPubkey = new PublicKey(agentPubkeyStr);
        const [agentPda] = deriveAgentPda(walletPda, agentPubkey);
        const agentAccount = await withRpcRetry(() => connection.getAccountInfo(agentPda));
        if (agentAccount) {
          tx.add(buildDeregisterAgentIx(ownerPubkey, walletPda, agentPda));
        }
      }
      tx.add(buildCloseWalletIx(ownerPubkey, walletPda));
      closesWallet = true;
    }

    if (tx.instructions.length === 0) {
      throw createApiError("No funds available to withdraw.", 404);
    }

    const { blockhash, lastValidBlockHeight } = await withRpcRetry(() =>
      connection.getLatestBlockhash("confirmed")
    );
    tx.recentBlockhash = blockhash;
    tx.lastValidBlockHeight = lastValidBlockHeight;

    // Backend signs with session signers
    for (const signer of signers) {
      tx.partialSign(signer);
    }

    const totalWithdrawLamports = sessionDrained + (closesWallet ? walletPdaLamports : 0);
    const withdrawSol = totalWithdrawLamports / LAMPORTS_PER_SOL;

    return c.json({
      success: true,
      transaction: tx.serialize({
        requireAllSignatures: false,
        verifySignatures: false,
      }).toString("base64"),
      network: config.SOLANA_NETWORK,
      withdrawSol: +withdrawSol.toFixed(6),
      totalAvailableSol: +(totalAvailable / LAMPORTS_PER_SOL).toFixed(6),
      walletPdaSol: +(walletPdaLamports / LAMPORTS_PER_SOL).toFixed(6),
      closesWallet,
      details: drainDetails.map((d) => ({
        botId: d.botId,
        name: d.name,
        sol: +(d.lamports / LAMPORTS_PER_SOL).toFixed(6),
      })),
      blockhash,
      lastValidBlockHeight,
    });
  }
);

// ═══════════════════════════════════════════════════════════════
// Submit a signed transaction
// ═══════════════════════════════════════════════════════════════

const submitSignedSchema = z.object({
  /** Base64-encoded fully-signed transaction */
  transaction: z.string().min(1),
  /** Optional bot ID for live-setup finalization after owner submission */
  setupLiveBotId: z.string().optional(),
  /** True when this signed TX is the owner-signed wallet recovery flow */
  recoverWalletClose: z.boolean().optional(),
});

/**
 * POST /wallet/submit-signed
 * Submit a fully-signed transaction to the Solana network.
 *
 * The Flutter app uses `signTransactions` (sign-only) and then
 * submits the signed TX via this endpoint.
 */
wallet.post(
  "/submit-signed",
  requireAuth,
  zValidator("json", submitSignedSchema),
  async (c) => {
    const userId = c.var.userId;
    const ownerAddress = c.var.walletAddress;
    const body = c.req.valid("json");
    const txBytes = Buffer.from(body.transaction, "base64");

    const connection = getConnection();
    try {
      const tx = Transaction.from(txBytes);
      const signature = await connection.sendRawTransaction(txBytes, {
        skipPreflight: true,
        maxRetries: 5,
      });

      // Poll for confirmation with generous timeout for mainnet.
      // Resend the TX periodically to improve landing probability.
      let confirmed = false;
      const TIMEOUT_MS = 90_000;       // 90 seconds max
      const POLL_INTERVAL_MS = 1_500;  // poll every 1.5s
      const RESEND_INTERVAL_MS = 8_000; // resend every 8s
      const startTime = Date.now();
      let lastResend = startTime;

      while (!confirmed && Date.now() - startTime < TIMEOUT_MS) {
        const { value } = await connection.getSignatureStatuses([signature]);
        const status = value[0];

        if (status?.err) {
          throw new Error(JSON.stringify(status.err));
        }

        if (
          status?.confirmationStatus === "confirmed" ||
          status?.confirmationStatus === "finalized"
        ) {
          confirmed = true;
          break;
        }

        // Resend periodically — mainnet validators may drop TXs
        if (Date.now() - lastResend >= RESEND_INTERVAL_MS) {
          try {
            await connection.sendRawTransaction(txBytes, {
              skipPreflight: true,
              maxRetries: 0,
            });
          } catch (_) {
            // best-effort resend
          }
          lastResend = Date.now();
        }

        await new Promise((resolve) => setTimeout(resolve, POLL_INTERVAL_MS));
      }

      if (!confirmed) {
        throw new Error(
          `Transaction was sent but not confirmed within ${Math.round(TIMEOUT_MS / 1000)}s ` +
          `(blockhash ${tx.recentBlockhash ?? "unknown"}). ` +
          `It may still land — check the signature: ${signature}`
        );
      }

      let finalizeResult:
        | {
          finalized: true;
          finalizeSignature: string;
          sessionAddress: string;
          sessionPubkey: string;
        }
        | undefined;

      if (body.setupLiveBotId) {
        const ownerPubkey = new PublicKey(ownerAddress);
        const walletPda = await getCanonicalWalletPda(userId, ownerPubkey);
        const [bot] = await db
          .select({
            positionSizeSOL: bots.positionSizeSOL,
            maxDailyLossSOL: bots.maxDailyLossSOL,
          })
          .from(bots)
          .where(and(eq(bots.botId, body.setupLiveBotId), eq(bots.userId, userId)));

        const finalized = await finalizeLiveSession({
          botId: body.setupLiveBotId,
          userId,
          walletPda,
          durationSecs: 7 * 24 * 60 * 60,
          // Session limits must NOT exceed the agent's daily_limit / per_tx_limit
          // that were set during RegisterAgent (same values used in setup-live).
          maxAmountSol: bot?.maxDailyLossSOL ?? 0.5,
          maxPerTxSol: bot?.positionSizeSOL ?? 0.1,
        });

        finalizeResult = {
          finalized: true,
          finalizeSignature: finalized.signature,
          sessionAddress: finalized.sessionAddress,
          sessionPubkey: finalized.sessionPubkey,
        };
      }

      if (body.recoverWalletClose == true) {
        await db.update(users)
          .set({
            sealWalletAddress: null,
            updatedAt: new Date(),
          })
          .where(eq(users.id, userId));

        await db.update(bots)
          .set({
            agentPubkey: null,
            agentConfigAddress: null,
            agentSecretKey: null,
            sessionAddress: null,
            sessionPubkey: null,
            sessionSecretKey: null,
            status: "stopped",
            lastError: null,
            updatedAt: new Date(),
          })
          .where(eq(bots.userId, userId));
      }

      return c.json({
        success: true,
        signature,
        ...finalizeResult,
        recoveredWalletClosed: body.recoverWalletClose == true,
      });
    } catch (e: any) {
      const msg = e?.message || e?.toString() || "Unknown error";
      throw createApiError(`Transaction submission failed: ${msg}`, 400);
    }
  }
);

export default wallet;
