/**
 * Seal wallet routes — proxy to on-chain wallet operations.
 *
 * These endpoints prepare unsigned (or sponsor-signed) transactions
 * that the Flutter app signs via MWA (Mobile Wallet Adapter) and submits.
 *
 * Sponsored mode: When Turnkey sponsor is configured, wallet creation
 * is paid by the sponsor wallet — the user only signs to prove ownership.
 */

import { Hono } from "hono";
import { z } from "zod";
import { zValidator } from "@hono/zod-validator";
import {
  PublicKey,
  Transaction,
  SystemProgram,
  Keypair,
  LAMPORTS_PER_SOL,
} from "@solana/web3.js";
import {
  ASSOCIATED_TOKEN_PROGRAM_ID,
  TOKEN_2022_PROGRAM_ID,
  TOKEN_PROGRAM_ID,
} from "@solana/spl-token";
import {
  getConnection,
  deriveWalletPda,
  deriveAgentPda,
  deriveSessionPda,
  SEAL_PROGRAM_ID,
  withRpcRetry,
} from "../services/solana.js";
import {
  isSponsorAvailable,
  getSponsorInfo,
  sponsorSign,
} from "../services/sponsor.js";
import { requireAuth, type AuthVariables } from "../middleware/auth.js";
import { createApiError } from "../middleware/error.js";
import config from "../config.js";
import db from "../db/index.js";
import { users, bots } from "../db/schema.js";
import { eq, and } from "drizzle-orm";

const wallet = new Hono<{ Variables: AuthVariables }>();

// ═══════════════════════════════════════════════════════════════
// Schemas
// ═══════════════════════════════════════════════════════════════

const createWalletSchema = z.object({
  dailyLimitSol: z.number().positive().max(1000).default(10),
  perTxLimitSol: z.number().positive().max(100).default(1),
});

const createAndFundSchema = z.object({
  dailyLimitSol: z.number().positive().max(1000).default(10),
  perTxLimitSol: z.number().positive().max(100).default(1),
  depositSol: z.number().positive().max(1000),
});

const depositSchema = z.object({
  amountSol: z.number().positive().max(1000),
});

const registerAgentSchema = z.object({
  /** Bot ID (8-char hex) to register as a Seal agent */
  botId: z.string().regex(/^[0-9a-f]{8}$/),
  /** Agent keypair public key (base58) — generated by the Flutter app */
  agentPubkey: z.string().min(32).max(50),
  /** Human-readable name for the agent (max 32 chars) */
  name: z.string().max(32).default("Sage Bot Agent"),
  /** Maximum SOL the agent can spend per day */
  dailyLimitSol: z.number().positive().max(1000).default(5),
  /** Maximum SOL the agent can spend per transaction */
  perTxLimitSol: z.number().positive().max(100).default(1),
  /** Additional program IDs to allow beyond backend defaults */
  allowedPrograms: z.array(z.string().min(32).max(50)).max(16).optional(),
});

const createSessionSchema = z.object({
  /** Bot ID that owns the agent for this session */
  botId: z.string().regex(/^[0-9a-f]{8}$/),
  /** Ephemeral session keypair pubkey (base58) — generated client-side */
  sessionPubkey: z.string().min(32).max(50),
  /** Session duration in seconds (max 7 days) */
  durationSecs: z.number().int().positive().max(7 * 24 * 60 * 60).default(24 * 60 * 60),
  /** Maximum SOL this session can spend total */
  maxAmountSol: z.number().positive().max(1000).default(5),
  /** Maximum SOL per individual transaction */
  maxPerTxSol: z.number().positive().max(100).default(1),
});

const revokeSessionSchema = z.object({
  /** Bot ID whose session to revoke */
  botId: z.string().regex(/^[0-9a-f]{8}$/),
});

// ═══════════════════════════════════════════════════════════════
// Discriminators & Account Parsing (from seal backend)
// ═══════════════════════════════════════════════════════════════

const SMART_WALLET_DISCRIMINATOR = Buffer.from("SealWalt");

function readU64LE(buf: Buffer, offset: number): bigint {
  return buf.readBigUInt64LE(offset);
}

function readI64LE(buf: Buffer, offset: number): bigint {
  return buf.readBigInt64LE(offset);
}

function readPubkey(buf: Buffer, offset: number): string {
  return new PublicKey(buf.subarray(offset, offset + 32)).toBase58();
}

interface SmartWalletState {
  address: string;
  pdaAuthority: string;
  owner: string;
  bump: number;
  nonce: string;
  agentCount: number;
  guardianCount: number;
  recoveryThreshold: number;
  guardians: string[];
  dailyLimitSol: number;
  perTxLimitSol: number;
  spentTodaySol: number;
  dayStartTimestamp: number;
  isLocked: boolean;
  isClosed: boolean;
}

const MEMO_PROGRAM_ID = new PublicKey(
  "MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr"
);

const CORE_AGENT_ALLOWED_PROGRAMS = [
  SystemProgram.programId,
  TOKEN_PROGRAM_ID,
  TOKEN_2022_PROGRAM_ID,
  ASSOCIATED_TOKEN_PROGRAM_ID,
  MEMO_PROGRAM_ID,
];

function parseConfiguredProgramIds(value?: string): PublicKey[] {
  if (!value) return [];

  return value
    .split(",")
    .map((programId) => programId.trim())
    .filter(Boolean)
    .map((programId) => new PublicKey(programId));
}

function uniquePubkeys(programs: PublicKey[]): PublicKey[] {
  const seen = new Set<string>();
  return programs.filter((program) => {
    const key = program.toBase58();
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

function getConfiguredAgentAllowlist(): PublicKey[] {
  const clusterSpecific =
    config.SOLANA_NETWORK === "mainnet-beta"
      ? config.SEAL_ALLOWED_PROGRAMS_MAINNET
      : config.SEAL_ALLOWED_PROGRAMS_DEVNET;

  return uniquePubkeys([
    ...CORE_AGENT_ALLOWED_PROGRAMS,
    ...parseConfiguredProgramIds(config.SEAL_ALLOWED_PROGRAMS),
    ...parseConfiguredProgramIds(clusterSpecific),
  ]);
}

function resolveAgentAllowedPrograms(extraPrograms?: string[]): PublicKey[] {
  const requestedPrograms = (extraPrograms ?? []).map(
    (programId) => new PublicKey(programId)
  );

  const allowedPrograms = uniquePubkeys([
    ...getConfiguredAgentAllowlist(),
    ...requestedPrograms,
  ]);

  const hasProtocolSpecificProgram = allowedPrograms.some(
    (program) =>
      !CORE_AGENT_ALLOWED_PROGRAMS.some((core) => core.equals(program))
  );

  if (!hasProtocolSpecificProgram) {
    throw createApiError(
      "Seal agent allowlist must include at least one protocol program. Configure SEAL_ALLOWED_PROGRAMS_MAINNET/DEVNET or pass allowedPrograms explicitly.",
      400
    );
  }

  return allowedPrograms;
}

async function getCanonicalWalletPda(
  userId: number,
  ownerPubkey: PublicKey,
  options?: { allowDerivedFallback?: boolean }
): Promise<PublicKey> {
  const [user] = await db
    .select({ sealWalletAddress: users.sealWalletAddress })
    .from(users)
    .where(eq(users.id, userId));

  if (user?.sealWalletAddress) {
    return new PublicKey(user.sealWalletAddress);
  }

  if (options?.allowDerivedFallback === false) {
    throw createApiError("Seal wallet address is not recorded for this user.", 409);
  }

  const [walletPda] = deriveWalletPda(ownerPubkey);
  return walletPda;
}

function parseSmartWallet(
  address: string,
  data: Buffer
): SmartWalletState | null {
  if (data.length < 278) return null;
  const disc = data.subarray(0, 8);
  if (!disc.equals(SMART_WALLET_DISCRIMINATOR)) return null;

  const guardianCount = data[82];
  const guardians: string[] = [];
  for (let i = 0; i < guardianCount && i < 5; i++) {
    guardians.push(readPubkey(data, 84 + i * 32));
  }

  return {
    address,
    pdaAuthority: readPubkey(data, 8),
    owner: readPubkey(data, 40),
    bump: data[72],
    nonce: readU64LE(data, 73).toString(),
    agentCount: data[81],
    guardianCount,
    recoveryThreshold: data[83],
    guardians,
    dailyLimitSol: Number(readU64LE(data, 244)) / LAMPORTS_PER_SOL,
    perTxLimitSol: Number(readU64LE(data, 252)) / LAMPORTS_PER_SOL,
    spentTodaySol: Number(readU64LE(data, 260)) / LAMPORTS_PER_SOL,
    dayStartTimestamp: Number(readI64LE(data, 268)),
    isLocked: data[276] !== 0,
    isClosed: data[277] !== 0,
  };
}

// ═══════════════════════════════════════════════════════════════
// Instruction Builder
// ═══════════════════════════════════════════════════════════════

function encodeU64(value: bigint): Buffer {
  const buf = Buffer.alloc(8);
  buf.writeBigUInt64LE(value);
  return buf;
}

function buildCreateWalletIx(
  funder: PublicKey,
  owner: PublicKey,
  walletPda: PublicKey,
  bump: number,
  dailyLimitLamports: bigint,
  perTxLimitLamports: bigint
) {
  const data = Buffer.concat([
    Buffer.from([0]), // CreateWallet discriminant
    Buffer.from([bump]),
    encodeU64(dailyLimitLamports),
    encodeU64(perTxLimitLamports),
  ]);

  return {
    programId: SEAL_PROGRAM_ID,
    keys: [
      { pubkey: funder, isSigner: true, isWritable: true },
      { pubkey: owner, isSigner: true, isWritable: false },
      { pubkey: walletPda, isSigner: false, isWritable: true },
      {
        pubkey: SystemProgram.programId,
        isSigner: false,
        isWritable: false,
      },
    ],
    data,
  };
}

// ═══════════════════════════════════════════════════════════════
// Routes (all require auth)
// ═══════════════════════════════════════════════════════════════

/**
 * POST /wallet/prepare-create
 * Prepare TX for Seal wallet creation.
 * When Turnkey sponsor is configured, the TX is partially signed by
 * the sponsor (user pays nothing). Otherwise, the user pays.
 */
wallet.post(
  "/prepare-create",
  requireAuth,
  zValidator("json", createWalletSchema),
  async (c) => {
    const ownerAddress = c.var.walletAddress;
    const body = c.req.valid("json");
    const ownerPubkey = new PublicKey(ownerAddress);

    const [walletPda, bump] = deriveWalletPda(ownerPubkey);

    // Check if wallet already exists (with retry for flaky RPC)
    const connection = getConnection();
    const existing = await withRpcRetry(() =>
      connection.getAccountInfo(walletPda)
    );
    if (existing) {
      throw createApiError("Seal wallet already exists", 409, {
        walletAddress: walletPda.toBase58(),
      });
    }

    const dailyLimitLamports = BigInt(
      Math.floor(body.dailyLimitSol * LAMPORTS_PER_SOL)
    );
    const perTxLimitLamports = BigInt(
      Math.floor(body.perTxLimitSol * LAMPORTS_PER_SOL)
    );

    const sponsored = await isSponsorAvailable();
    const funderPubkey = sponsored
      ? (await getSponsorInfo()).publicKey
      : ownerPubkey;

    const ix = buildCreateWalletIx(
      funderPubkey,
      ownerPubkey,
      walletPda,
      bump,
      dailyLimitLamports,
      perTxLimitLamports
    );

    const { blockhash, lastValidBlockHeight } =
      await withRpcRetry(() => connection.getLatestBlockhash());

    const tx = new Transaction();
    tx.add(ix);
    tx.recentBlockhash = blockhash;
    tx.feePayer = funderPubkey;

    // If sponsor is available, partially sign so the user only
    // needs to add their MWA signature.
    if (sponsored) {
      await sponsorSign(tx);
    }

    const serialized = tx
      .serialize({ requireAllSignatures: false })
      .toString("base64");

    // Store seal wallet address in user record
    await db.update(users)
      .set({ sealWalletAddress: walletPda.toBase58() })
      .where(eq(users.walletAddress, ownerAddress));

    return c.json({
      success: true,
      walletAddress: walletPda.toBase58(),
      transaction: serialized,
      sponsored,
      network: config.SOLANA_NETWORK,
      blockhash,
      lastValidBlockHeight,
    });
  }
);

/**
 * GET /wallet/state
 * Get authenticated user's Seal wallet state.
 */
wallet.get("/state", requireAuth, async (c) => {
  const userId = c.var.userId;
  const ownerAddress = c.var.walletAddress;
  const ownerPubkey = new PublicKey(ownerAddress);
  const walletPda = await getCanonicalWalletPda(userId, ownerPubkey);

  const connection = getConnection();
  const accountInfo = await withRpcRetry(() =>
    connection.getAccountInfo(walletPda)
  );

  if (!accountInfo) {
    return c.json({
      success: true,
      exists: false,
      walletAddress: walletPda.toBase58(),
    });
  }

  const walletState = parseSmartWallet(
    walletPda.toBase58(),
    accountInfo.data as Buffer
  );

  return c.json({ success: true, exists: true, wallet: walletState });
});

/**
 * GET /wallet/balance
 * Get SOL balance of authenticated user's Seal wallet.
 */
wallet.get("/balance", requireAuth, async (c) => {
  const userId = c.var.userId;
  const ownerAddress = c.var.walletAddress;
  const ownerPubkey = new PublicKey(ownerAddress);
  const walletPda = await getCanonicalWalletPda(userId, ownerPubkey);

  const connection = getConnection();
  const lamports = await connection.getBalance(walletPda);

  return c.json({
    success: true,
    lamports,
    sol: lamports / LAMPORTS_PER_SOL,
  });
});

/**
 * POST /wallet/prepare-create-and-fund
 * Prepare a TX that creates a Seal wallet AND transfers SOL into it.
 * Wallet creation rent is sponsored (when Turnkey is configured).
 * The SOL deposit always comes from the user.
 */
wallet.post(
  "/prepare-create-and-fund",
  requireAuth,
  zValidator("json", createAndFundSchema),
  async (c) => {
    const ownerAddress = c.var.walletAddress;
    const body = c.req.valid("json");
    const ownerPubkey = new PublicKey(ownerAddress);

    const [walletPda, bump] = deriveWalletPda(ownerPubkey);

    // Check if wallet already exists
    const connection = getConnection();
    const existing = await withRpcRetry(() =>
      connection.getAccountInfo(walletPda)
    );
    if (existing) {
      throw createApiError("Seal wallet already exists", 409, {
        walletAddress: walletPda.toBase58(),
      });
    }

    const dailyLimitLamports = BigInt(
      Math.floor(body.dailyLimitSol * LAMPORTS_PER_SOL)
    );
    const perTxLimitLamports = BigInt(
      Math.floor(body.perTxLimitSol * LAMPORTS_PER_SOL)
    );
    const depositLamports = BigInt(
      Math.floor(body.depositSol * LAMPORTS_PER_SOL)
    );

    const sponsored = await isSponsorAvailable();
    const funderPubkey = sponsored
      ? (await getSponsorInfo()).publicKey
      : ownerPubkey;

    // Instruction 1: Create wallet PDA (sponsor pays rent if available)
    const createIx = buildCreateWalletIx(
      funderPubkey,
      ownerPubkey,
      walletPda,
      bump,
      dailyLimitLamports,
      perTxLimitLamports
    );

    // Instruction 2: Transfer SOL from user → wallet PDA (user always pays deposit)
    const transferIx = SystemProgram.transfer({
      fromPubkey: ownerPubkey,
      toPubkey: walletPda,
      lamports: depositLamports,
    });

    const { blockhash, lastValidBlockHeight } =
      await withRpcRetry(() => connection.getLatestBlockhash());

    const tx = new Transaction();
    tx.add(createIx);
    tx.add(transferIx);
    tx.recentBlockhash = blockhash;
    // Fee payer is sponsor when available, otherwise the user
    tx.feePayer = funderPubkey;

    if (sponsored) {
      await sponsorSign(tx);
    }

    const serialized = tx
      .serialize({ requireAllSignatures: false })
      .toString("base64");

    // Store seal wallet address in user record
    await db.update(users)
      .set({ sealWalletAddress: walletPda.toBase58() })
      .where(eq(users.walletAddress, ownerAddress));

    return c.json({
      success: true,
      walletAddress: walletPda.toBase58(),
      transaction: serialized,
      sponsored,
      depositSol: body.depositSol,
      network: config.SOLANA_NETWORK,
      blockhash,
      lastValidBlockHeight,
    });
  }
);

/**
 * POST /wallet/prepare-deposit
 * Prepare an unsigned SystemProgram.transfer TX to fund an existing
 * Seal wallet with additional SOL.
 */
wallet.post(
  "/prepare-deposit",
  requireAuth,
  zValidator("json", depositSchema),
  async (c) => {
    const userId = c.var.userId;
    const ownerAddress = c.var.walletAddress;
    const body = c.req.valid("json");
    const ownerPubkey = new PublicKey(ownerAddress);

    const walletPda = await getCanonicalWalletPda(userId, ownerPubkey);

    // Verify wallet exists
    const connection = getConnection();
    const existing = await withRpcRetry(() =>
      connection.getAccountInfo(walletPda)
    );
    if (!existing) {
      throw createApiError(
        "Seal wallet not found. Create one first.",
        404
      );
    }

    const depositLamports = BigInt(
      Math.floor(body.amountSol * LAMPORTS_PER_SOL)
    );

    const transferIx = SystemProgram.transfer({
      fromPubkey: ownerPubkey,
      toPubkey: walletPda,
      lamports: depositLamports,
    });

    const { blockhash, lastValidBlockHeight } =
      await withRpcRetry(() => connection.getLatestBlockhash());

    const tx = new Transaction();
    tx.add(transferIx);
    tx.recentBlockhash = blockhash;
    tx.feePayer = ownerPubkey;

    const serialized = tx
      .serialize({ requireAllSignatures: false })
      .toString("base64");

    return c.json({
      success: true,
      walletAddress: walletPda.toBase58(),
      transaction: serialized,
      depositSol: body.amountSol,
      blockhash,
      lastValidBlockHeight,
    });
  }
);

/**
 * GET /wallet/sponsor-status
 * Check if sponsored wallet creation is available.
 * The Flutter app uses this to decide whether to show "Free wallet"
 * or "You'll pay ~0.003 SOL" in the UI.
 */
wallet.get("/sponsor-status", requireAuth, async (c) => {
  const available = await isSponsorAvailable();
  const info = available ? await getSponsorInfo() : null;
  return c.json({
    success: true,
    sponsored: available,
    sponsor: info?.address ?? null,
    strategy: info?.strategy ?? null,
  });
});

// ═══════════════════════════════════════════════════════════════
// Per-Bot Agent Registration
// ═══════════════════════════════════════════════════════════════

/** Encode a string as fixed-length bytes (zero-padded) — matches seal-ts */
function encodeFixedString(str: string, length: number): Buffer {
  const buf = Buffer.alloc(length);
  buf.write(str, "utf-8");
  return buf;
}

/** Encode an i64 as little-endian 8 bytes */
function encodeI64(value: bigint): Buffer {
  const buf = Buffer.alloc(8);
  buf.writeBigInt64LE(value);
  return buf;
}

const MAX_AGENT_NAME_LENGTH = 32;

/**
 * Build a RegisterAgent instruction (discriminant = 1).
 *
 * Binary layout:
 *   [0]       disc (1)
 *   [1]       bump
 *   [2..33]   agent pubkey (32 bytes)
 *   [34..65]  name (32 bytes, zero-padded)
 *   [66]      allowedPrograms count
 *   [67..]    allowedPrograms (32 bytes each)
 *   [N]       allowedInstructions count
 *   [N+1..]   allowedInstructions (8 bytes each)
 *   [..]      dailyLimit (u64le)
 *   [..]      perTxLimit (u64le)
 *   [..]      defaultSessionDuration (i64le)
 *   [..]      maxSessionDuration (i64le)
 */
function buildRegisterAgentIx(
  owner: PublicKey,
  walletPda: PublicKey,
  agentPubkey: PublicKey,
  agentPda: PublicKey,
  bump: number,
  name: string,
  dailyLimitLamports: bigint,
  perTxLimitLamports: bigint,
  allowedPrograms: PublicKey[] = [],
  allowedInstructions: Buffer[] = []
) {
  // Defaults matching seal-ts
  const defaultSessionDuration = BigInt(24 * 60 * 60); // 24 hours
  const maxSessionDuration = BigInt(7 * 24 * 60 * 60); // 7 days

  const data = Buffer.concat([
    Buffer.from([1]), // InstructionDiscriminant.RegisterAgent
    Buffer.from([bump]),
    agentPubkey.toBuffer(),
    encodeFixedString(name, MAX_AGENT_NAME_LENGTH),
    Buffer.from([allowedPrograms.length]),
    ...allowedPrograms.map((programId) => programId.toBuffer()),
    Buffer.from([allowedInstructions.length]),
    ...allowedInstructions,
    encodeU64(dailyLimitLamports),
    encodeU64(perTxLimitLamports),
    encodeI64(defaultSessionDuration),
    encodeI64(maxSessionDuration),
  ]);

  return {
    programId: SEAL_PROGRAM_ID,
    keys: [
      { pubkey: owner, isSigner: true, isWritable: true },
      { pubkey: walletPda, isSigner: false, isWritable: true },
      { pubkey: agentPda, isSigner: false, isWritable: true },
      {
        pubkey: SystemProgram.programId,
        isSigner: false,
        isWritable: false,
      },
    ],
    data,
  };
}

/**
 * Build a CreateSession instruction (discriminant = 2).
 *
 * On-chain layout (57 bytes):
 *   [0]       disc (2)
 *   [1]       bump
 *   [2..33]   session_pubkey (32 bytes)
 *   [34..41]  duration_secs (i64 LE)
 *   [42..49]  max_amount_lamports (u64 LE)
 *   [50..57]  max_per_tx_lamports (u64 LE)
 *
 * Accounts (matching seal program create_session.rs):
 *   0. [signer, writable] Agent
 *   1. []                 SmartWallet PDA
 *   2. []                 AgentConfig PDA
 *   3. [writable]         SessionKey PDA
 *   4. []                 System Program
 */
function buildCreateSessionIx(
  agentPubkey: PublicKey,
  walletPda: PublicKey,
  agentPda: PublicKey,
  sessionPda: PublicKey,
  bump: number,
  sessionPubkey: PublicKey,
  durationSecs: bigint,
  maxAmountLamports: bigint,
  maxPerTxLamports: bigint
) {
  const data = Buffer.concat([
    Buffer.from([2]), // InstructionDiscriminant.CreateSessionKey
    Buffer.from([bump]),
    sessionPubkey.toBuffer(),
    encodeI64(durationSecs),
    encodeU64(maxAmountLamports),
    encodeU64(maxPerTxLamports),
  ]);

  return {
    programId: SEAL_PROGRAM_ID,
    keys: [
      { pubkey: agentPubkey, isSigner: true, isWritable: true },
      { pubkey: walletPda, isSigner: false, isWritable: false },
      { pubkey: agentPda, isSigner: false, isWritable: false },
      { pubkey: sessionPda, isSigner: false, isWritable: true },
      {
        pubkey: SystemProgram.programId,
        isSigner: false,
        isWritable: false,
      },
    ],
    data,
  };
}

/**
 * Build a RevokeSession instruction (discriminant = 4).
 *
 * On-chain layout (1 byte):
 *   [0]  disc (4)
 *
 * Accounts (matching seal program revoke_session.rs):
 *   0. [signer]    Authority (wallet owner OR agent)
 *   1. [writable]  SessionKey PDA
 *   2. []          SmartWallet PDA
 */
function buildRevokeSessionIx(
  authority: PublicKey,
  sessionPda: PublicKey,
  walletPda: PublicKey
) {
  const data = Buffer.from([4]); // InstructionDiscriminant.RevokeSession

  return {
    programId: SEAL_PROGRAM_ID,
    keys: [
      { pubkey: authority, isSigner: true, isWritable: false },
      { pubkey: sessionPda, isSigner: false, isWritable: true },
      { pubkey: walletPda, isSigner: false, isWritable: false },
    ],
    data,
  };
}

/**
 * POST /wallet/prepare-register-agent
 * Prepare TX to register a bot as a Seal agent on the user's wallet.
 *
 * Flow:
 * 1. Validate the bot exists, belongs to the user, and is live mode
 * 2. Derive the AgentConfig PDA
 * 3. Build the RegisterAgent instruction
 * 4. Optionally sponsor-sign
 * 5. Return serialized TX for MWA signing
 * 6. Store agentPubkey + agentConfigAddress in the bot row
 */
wallet.post(
  "/prepare-register-agent",
  requireAuth,
  zValidator("json", registerAgentSchema),
  async (c) => {
    const userId = c.var.userId;
    const ownerAddress = c.var.walletAddress;
    const body = c.req.valid("json");

    const ownerPubkey = new PublicKey(ownerAddress);
    const agentPubkey = new PublicKey(body.agentPubkey);
    const allowedPrograms = resolveAgentAllowedPrograms(body.allowedPrograms);

    // ── Validate bot ──
    const [bot] = await db
      .select()
      .from(bots)
      .where(and(eq(bots.botId, body.botId), eq(bots.userId, userId)));

    if (!bot) {
      throw createApiError("Bot not found", 404);
    }

    if (bot.mode !== "live") {
      throw createApiError(
        "Agent registration is only required for live-mode bots",
        400
      );
    }

    if (bot.agentPubkey) {
      throw createApiError("Bot already has an agent registered", 409, {
        agentPubkey: bot.agentPubkey,
        agentConfigAddress: bot.agentConfigAddress,
      });
    }

    // ── Verify Seal wallet exists ──
    const walletPda = await getCanonicalWalletPda(userId, ownerPubkey);
    const connection = getConnection();
    const walletAccount = await withRpcRetry(() =>
      connection.getAccountInfo(walletPda)
    );
    if (!walletAccount) {
      throw createApiError(
        "Seal wallet not found. Create one first.",
        404
      );
    }

    // ── Derive agent PDA ──
    const [agentPda, bump] = deriveAgentPda(walletPda, agentPubkey);

    // Check if agent PDA already exists on-chain
    const existingAgent = await withRpcRetry(() =>
      connection.getAccountInfo(agentPda)
    );
    if (existingAgent) {
      throw createApiError("Agent account already exists on-chain", 409, {
        agentConfigAddress: agentPda.toBase58(),
      });
    }

    // ── Build TX ──
    const dailyLimitLamports = BigInt(
      Math.floor(body.dailyLimitSol * LAMPORTS_PER_SOL)
    );
    const perTxLimitLamports = BigInt(
      Math.floor(body.perTxLimitSol * LAMPORTS_PER_SOL)
    );

    const sponsored = await isSponsorAvailable();
    const funderPubkey = sponsored
      ? (await getSponsorInfo()).publicKey
      : ownerPubkey;

    const ix = buildRegisterAgentIx(
      ownerPubkey,
      walletPda,
      agentPubkey,
      agentPda,
      bump,
      body.name,
      dailyLimitLamports,
      perTxLimitLamports,
      allowedPrograms
    );

    const { blockhash, lastValidBlockHeight } = await withRpcRetry(() =>
      connection.getLatestBlockhash()
    );

    const tx = new Transaction();
    tx.add(ix);
    tx.recentBlockhash = blockhash;
    tx.feePayer = funderPubkey;

    if (sponsored) {
      await sponsorSign(tx);
    }

    const serialized = tx
      .serialize({ requireAllSignatures: false })
      .toString("base64");

    // ── Persist agent info in bot row ──
    await db.update(bots)
      .set({
        agentPubkey: agentPubkey.toBase58(),
        agentConfigAddress: agentPda.toBase58(),
        updatedAt: new Date(),
      })
      .where(eq(bots.botId, body.botId));

    return c.json({
      success: true,
      botId: body.botId,
      agentPubkey: agentPubkey.toBase58(),
      agentConfigAddress: agentPda.toBase58(),
      allowedPrograms: allowedPrograms.map((programId) => programId.toBase58()),
      transaction: serialized,
      sponsored,
      network: config.SOLANA_NETWORK,
      blockhash,
      lastValidBlockHeight,
    });
  }
);

// ═══════════════════════════════════════════════════════════════
// Session Key Management
// ═══════════════════════════════════════════════════════════════

/**
 * POST /wallet/prepare-create-session
 * Prepare TX to create a session key for an agent.
 *
 * The agent (bot keypair) is the signer/payer for session creation on-chain.
 * However, since the Flutter app signs via MWA (owner wallet), we prepare
 * the TX for the OWNER to sign — the agent keypair is stored server-side
 * and we don't require it to sign here. The Flutter app must ensure the
 * agent keypair also signs before submission.
 *
 * Flow:
 * 1. Validate bot exists, belongs to user, and has a registered agent
 * 2. Verify the bot doesn't already have an active session
 * 3. Derive the SessionKey PDA from (walletPda, agentPubkey, sessionPubkey)
 * 4. Build CreateSession instruction
 * 5. Return serialized TX for client-side signing (agent signs)
 * 6. Store sessionAddress in bot row
 */
wallet.post(
  "/prepare-create-session",
  requireAuth,
  zValidator("json", createSessionSchema),
  async (c) => {
    const userId = c.var.userId;
    const ownerAddress = c.var.walletAddress;
    const body = c.req.valid("json");

    const ownerPubkey = new PublicKey(ownerAddress);
    const sessionPubkey = new PublicKey(body.sessionPubkey);

    // ── Validate bot ──
    const [bot] = await db
      .select()
      .from(bots)
      .where(and(eq(bots.botId, body.botId), eq(bots.userId, userId)));

    if (!bot) {
      throw createApiError("Bot not found", 404);
    }

    if (bot.mode !== "live") {
      throw createApiError(
        "Session keys are only used for live-mode bots",
        400
      );
    }

    if (!bot.agentPubkey || !bot.agentConfigAddress) {
      throw createApiError(
        "Bot must have a registered agent before creating a session. " +
        "Use /wallet/prepare-register-agent first.",
        400
      );
    }

    if (bot.sessionAddress) {
      throw createApiError("Bot already has an active session", 409, {
        sessionAddress: bot.sessionAddress,
      });
    }

    // ── Verify Seal wallet exists on-chain ──
    const walletPda = await getCanonicalWalletPda(userId, ownerPubkey);
    const connection = getConnection();
    const walletAccount = await withRpcRetry(() =>
      connection.getAccountInfo(walletPda)
    );
    if (!walletAccount) {
      throw createApiError(
        "Seal wallet not found. Create one first.",
        404
      );
    }

    // ── Derive PDAs ──
    const agentPubkey = new PublicKey(bot.agentPubkey);
    const [agentPda] = deriveAgentPda(walletPda, agentPubkey);

    // Verify agent config exists on-chain
    const agentAccount = await withRpcRetry(() =>
      connection.getAccountInfo(agentPda)
    );
    if (!agentAccount) {
      throw createApiError(
        "Agent config not found on-chain. Register the agent first.",
        404,
        { expectedAddress: agentPda.toBase58() }
      );
    }

    const [sessionPda, bump] = deriveSessionPda(
      walletPda,
      agentPubkey,
      sessionPubkey
    );

    // Verify session PDA doesn't already exist on-chain
    const existingSession = await withRpcRetry(() =>
      connection.getAccountInfo(sessionPda)
    );
    if (existingSession) {
      throw createApiError("Session account already exists on-chain", 409, {
        sessionAddress: sessionPda.toBase58(),
      });
    }

    // ── Build TX ──
    const durationSecs = BigInt(body.durationSecs);
    const maxAmountLamports = BigInt(
      Math.floor(body.maxAmountSol * LAMPORTS_PER_SOL)
    );
    const maxPerTxLamports = BigInt(
      Math.floor(body.maxPerTxSol * LAMPORTS_PER_SOL)
    );

    // Validate spending limits: session limits should not exceed what
    // was set at agent registration level
    if (maxPerTxLamports > maxAmountLamports) {
      throw createApiError(
        "maxPerTxSol cannot exceed maxAmountSol",
        400
      );
    }

    const ix = buildCreateSessionIx(
      agentPubkey,  // agent is signer/payer on-chain
      walletPda,
      agentPda,
      sessionPda,
      bump,
      sessionPubkey,
      durationSecs,
      maxAmountLamports,
      maxPerTxLamports
    );

    const { blockhash, lastValidBlockHeight } = await withRpcRetry(() =>
      connection.getLatestBlockhash()
    );

    const tx = new Transaction();
    tx.add(ix);
    tx.recentBlockhash = blockhash;
    // Agent is the fee payer for session creation (they're the signer on-chain)
    tx.feePayer = agentPubkey;

    const serialized = tx
      .serialize({ requireAllSignatures: false })
      .toString("base64");

    // ── Persist session info in bot row ──
    await db.update(bots)
      .set({
        sessionAddress: sessionPda.toBase58(),
        updatedAt: new Date(),
      })
      .where(eq(bots.botId, body.botId));

    return c.json({
      success: true,
      botId: body.botId,
      sessionAddress: sessionPda.toBase58(),
      sessionPubkey: sessionPubkey.toBase58(),
      agentPubkey: bot.agentPubkey,
      durationSecs: body.durationSecs,
      maxAmountSol: body.maxAmountSol,
      maxPerTxSol: body.maxPerTxSol,
      transaction: serialized,
      blockhash,
      lastValidBlockHeight,
    });
  }
);

// ═══════════════════════════════════════════════════════════════
// Combined Live Setup (Agent + Session in one TX)
// ═══════════════════════════════════════════════════════════════

const setupLiveSchema = z.object({
  botId: z.string(),
  /** Agent spending limits */
  dailyLimitSol: z.number().positive().max(1000).default(10),
  perTxLimitSol: z.number().positive().max(100).default(2),
  /** Session config */
  sessionDurationSecs: z.number().int().positive().default(7 * 24 * 60 * 60), // 7 days
  sessionMaxAmountSol: z.number().positive().default(100),
  sessionMaxPerTxSol: z.number().positive().default(2),
  allowedPrograms: z.array(z.string().min(32).max(50)).max(16).optional(),
});

/**
 * POST /wallet/setup-live
 * One-shot live mode setup: generates agent + session keypairs SERVER-SIDE,
 * builds RegisterAgent + CreateSession in a single TX.
 *
 * The backend signs with the agent keypair. Flutter signs with the owner
 * via MWA. One MWA popup → agent + session both created atomically.
 *
 * Flow:
 * 1. Validate bot exists, belongs to user, is live mode, no agent yet
 * 2. Generate agent keypair + session keypair (server-side)
 * 3. Store private keys in DB (encrypted in production)
 * 4. Build RegisterAgent IX (owner signs) + CreateSession IX (agent signs)
 * 5. Combine in one TX, agent-sign server-side
 * 6. Return partially-signed TX for MWA signing
 *
 * After MWA signing + submission, the bot has an active session key
 * and the orchestrator can use it to sign executeViaSession trades.
 */
wallet.post(
  "/setup-live",
  requireAuth,
  zValidator("json", setupLiveSchema),
  async (c) => {
    const userId = c.var.userId;
    const ownerAddress = c.var.walletAddress;
    const body = c.req.valid("json");

    const ownerPubkey = new PublicKey(ownerAddress);
    const allowedPrograms = resolveAgentAllowedPrograms(body.allowedPrograms);

    // ── Validate bot ──
    const [bot] = await db
      .select()
      .from(bots)
      .where(and(eq(bots.botId, body.botId), eq(bots.userId, userId)));

    if (!bot) {
      throw createApiError("Bot not found", 404);
    }

    if (bot.mode !== "live") {
      throw createApiError(
        "Live setup is only for live-mode bots",
        400
      );
    }

    if (bot.agentPubkey && bot.sessionAddress) {
      throw createApiError("Bot already has agent + session configured", 409, {
        agentPubkey: bot.agentPubkey,
        sessionAddress: bot.sessionAddress,
      });
    }

    // ── Verify Seal wallet exists on-chain ──
    const walletPda = await getCanonicalWalletPda(userId, ownerPubkey);
    const connection = getConnection();
    const walletAccount = await withRpcRetry(() =>
      connection.getAccountInfo(walletPda)
    );
    if (!walletAccount) {
      throw createApiError(
        "Seal wallet not found. Create one first.",
        404
      );
    }

    // ── Generate keypairs server-side ──
    const agentKeypair = Keypair.generate();
    const sessionKeypair = Keypair.generate();

    // ── Derive PDAs ──
    const [agentPda, agentBump] = deriveAgentPda(walletPda, agentKeypair.publicKey);
    const [sessionPda, sessionBump] = deriveSessionPda(
      walletPda,
      agentKeypair.publicKey,
      sessionKeypair.publicKey
    );

    // Verify neither PDA exists on-chain
    const [existingAgent, existingSession] = await Promise.all([
      withRpcRetry(() => connection.getAccountInfo(agentPda)),
      withRpcRetry(() => connection.getAccountInfo(sessionPda)),
    ]);
    if (existingAgent) {
      throw createApiError("Agent account already exists on-chain", 409);
    }
    if (existingSession) {
      throw createApiError("Session account already exists on-chain", 409);
    }

    // ── Build RegisterAgent IX ──
    const dailyLimitLamports = BigInt(
      Math.floor(body.dailyLimitSol * LAMPORTS_PER_SOL)
    );
    const perTxLimitLamports = BigInt(
      Math.floor(body.perTxLimitSol * LAMPORTS_PER_SOL)
    );

    const registerIx = buildRegisterAgentIx(
      ownerPubkey,
      walletPda,
      agentKeypair.publicKey,
      agentPda,
      agentBump,
      `bot-${body.botId}`,
      dailyLimitLamports,
      perTxLimitLamports,
      allowedPrograms
    );

    // ── Build CreateSession IX ──
    const sessionDurationSecs = BigInt(body.sessionDurationSecs);
    const sessionMaxAmountLamports = BigInt(
      Math.floor(body.sessionMaxAmountSol * LAMPORTS_PER_SOL)
    );
    const sessionMaxPerTxLamports = BigInt(
      Math.floor(body.sessionMaxPerTxSol * LAMPORTS_PER_SOL)
    );

    const createSessionIx = buildCreateSessionIx(
      agentKeypair.publicKey,
      walletPda,
      agentPda,
      sessionPda,
      sessionBump,
      sessionKeypair.publicKey,
      sessionDurationSecs,
      sessionMaxAmountLamports,
      sessionMaxPerTxLamports
    );

    // ── Assemble TX ──
    const { blockhash, lastValidBlockHeight } = await withRpcRetry(() =>
      connection.getLatestBlockhash()
    );

    // Determine fee payer: prefer sponsor if available AND funded,
    // otherwise the owner pays (they sign via MWA anyway).
    let sponsored = await isSponsorAvailable();
    let funderPubkey = ownerPubkey;

    if (sponsored) {
      const sponsorInfo = await getSponsorInfo();
      const sponsorBalance = await withRpcRetry(() =>
        connection.getBalance(sponsorInfo.publicKey)
      );
      // Need enough for: TX fees (~15k) + agent funding (~102k) = ~120k total
      const MIN_SPONSOR_BALANCE = 50_000_000; // 0.05 SOL (safety margin for multiple ops)
      if (sponsorBalance >= MIN_SPONSOR_BALANCE) {
        funderPubkey = sponsorInfo.publicKey;
      } else {
        // Sponsor exists but not funded on this network — fall back to owner
        sponsored = false;
        funderPubkey = ownerPubkey;
        console.warn(
          `⚠️  Sponsor balance (${sponsorBalance} lamports) below minimum ` +
          `(${MIN_SPONSOR_BALANCE}) on ${config.SOLANA_NETWORK}. Owner will pay setup costs.`
        );
      }
    }

    // The agent keypair needs SOL to pay rent for the SessionKey PDA.
    // SessionKey account is 154 bytes → ~0.0015 SOL rent-exempt minimum.
    // We transfer a small buffer (0.003 SOL) from the fee payer to the
    // agent so it can fund the create_account CPI inside CreateSession.
    const sessionRentLamports = await withRpcRetry(() =>
      connection.getMinimumBalanceForRentExemption(154) // SessionKey::SIZE
    );
    // Add a small buffer for compute budget
    const agentFundingLamports = sessionRentLamports + 100_000; // ~0.0001 SOL extra

    const fundAgentIx = SystemProgram.transfer({
      fromPubkey: funderPubkey,
      toPubkey: agentKeypair.publicKey,
      lamports: agentFundingLamports,
    });

    const tx = new Transaction();
    tx.add(fundAgentIx);    // 1. Fund agent so it can pay session PDA rent
    tx.add(registerIx);     // 2. Owner registers agent on wallet
    tx.add(createSessionIx); // 3. Agent creates session key
    tx.recentBlockhash = blockhash;
    tx.feePayer = funderPubkey;

    // Backend signs with agent keypair (CreateSession requires agent as signer)
    tx.partialSign(agentKeypair);

    // Optionally sponsor-sign
    if (sponsored) {
      await sponsorSign(tx);
    }

    const serialized = tx
      .serialize({ requireAllSignatures: false })
      .toString("base64");

    // ── Persist keys in DB ──
    // Store private keys as base64-encoded Uint8Array (64 bytes: seed + pubkey)
    await db.update(bots)
      .set({
        agentPubkey: agentKeypair.publicKey.toBase58(),
        agentSecretKey: Buffer.from(agentKeypair.secretKey).toString("base64"),
        agentConfigAddress: agentPda.toBase58(),
        sessionAddress: sessionPda.toBase58(),
        sessionPubkey: sessionKeypair.publicKey.toBase58(),
        sessionSecretKey: Buffer.from(sessionKeypair.secretKey).toString("base64"),
        updatedAt: new Date(),
      })
      .where(eq(bots.botId, body.botId));

    return c.json({
      success: true,
      botId: body.botId,
      agentPubkey: agentKeypair.publicKey.toBase58(),
      agentConfigAddress: agentPda.toBase58(),
      sessionAddress: sessionPda.toBase58(),
      sessionPubkey: sessionKeypair.publicKey.toBase58(),
      allowedPrograms: allowedPrograms.map((programId) => programId.toBase58()),
      transaction: serialized,
      sponsored,
      network: config.SOLANA_NETWORK,
      blockhash,
      lastValidBlockHeight,
    });
  }
);

/**
 * POST /wallet/prepare-revoke-session
 * Prepare TX to revoke an active session key.
 *
 * Either the wallet owner or the agent can revoke a session.
 * This endpoint prepares the TX for the owner to sign via MWA.
 *
 * Flow:
 * 1. Validate bot exists, belongs to user, and has an active session
 * 2. Load the on-chain session account to extract agent + sessionPubkey
 * 3. Build RevokeSession instruction (owner as authority)
 * 4. Return serialized TX for MWA signing
 * 5. Clear sessionAddress from bot row
 */
wallet.post(
  "/prepare-revoke-session",
  requireAuth,
  zValidator("json", revokeSessionSchema),
  async (c) => {
    const userId = c.var.userId;
    const ownerAddress = c.var.walletAddress;
    const body = c.req.valid("json");

    const ownerPubkey = new PublicKey(ownerAddress);

    // ── Validate bot ──
    const [bot] = await db
      .select()
      .from(bots)
      .where(and(eq(bots.botId, body.botId), eq(bots.userId, userId)));

    if (!bot) {
      throw createApiError("Bot not found", 404);
    }

    if (!bot.sessionAddress) {
      throw createApiError("Bot has no active session to revoke", 400);
    }

    // ── Verify session account exists on-chain ──
    const sessionPda = new PublicKey(bot.sessionAddress);
    const connection = getConnection();
    const sessionAccount = await withRpcRetry(() =>
      connection.getAccountInfo(sessionPda)
    );

    if (!sessionAccount) {
      // Session doesn't exist on-chain — clean up DB and return success
      await db.update(bots)
        .set({
          sessionAddress: null,
          updatedAt: new Date(),
        })
        .where(eq(bots.botId, body.botId));

      return c.json({
        success: true,
        botId: body.botId,
        message: "Session already closed on-chain. Database cleaned up.",
        alreadyClosed: true,
      });
    }

    // Parse session to check if already revoked
    const sessionData = sessionAccount.data as Buffer;
    if (sessionData.length < 154) {
      throw createApiError("Invalid session account data", 500);
    }

    const isRevoked = sessionData[145] !== 0; // offset: 8(disc)+32(wallet)+32(agent)+32(session)+1(bump)+8(created)+8(expires)+8(max)+8(spent)+8(perTx) = 145
    if (isRevoked) {
      // Already revoked on-chain — clean up DB
      await db.update(bots)
        .set({
          sessionAddress: null,
          updatedAt: new Date(),
        })
        .where(eq(bots.botId, body.botId));

      return c.json({
        success: true,
        botId: body.botId,
        message: "Session was already revoked on-chain. Database cleaned up.",
        alreadyRevoked: true,
      });
    }

    // ── Build TX ──
    const walletPda = await getCanonicalWalletPda(userId, ownerPubkey);

    const ix = buildRevokeSessionIx(
      ownerPubkey, // owner as authority
      sessionPda,
      walletPda
    );

    const { blockhash, lastValidBlockHeight } = await withRpcRetry(() =>
      connection.getLatestBlockhash()
    );

    const tx = new Transaction();
    tx.add(ix);
    tx.recentBlockhash = blockhash;
    tx.feePayer = ownerPubkey;

    const serialized = tx
      .serialize({ requireAllSignatures: false })
      .toString("base64");

    // ── Clear session from bot row ──
    await db.update(bots)
      .set({
        sessionAddress: null,
        updatedAt: new Date(),
      })
      .where(eq(bots.botId, body.botId));

    return c.json({
      success: true,
      botId: body.botId,
      sessionAddress: bot.sessionAddress,
      transaction: serialized,
      network: config.SOLANA_NETWORK,
      blockhash,
      lastValidBlockHeight,
    });
  }
);

// ═══════════════════════════════════════════════════════════════
// Submit a signed transaction
// ═══════════════════════════════════════════════════════════════

const submitSignedSchema = z.object({
  /** Base64-encoded fully-signed transaction */
  transaction: z.string().min(1),
});

/**
 * POST /wallet/submit-signed
 * Submit a fully-signed transaction to the Solana network.
 *
 * This is used as a fallback when `signAndSendTransactions` fails
 * (e.g. Phantom simulation failure for sponsored/devnet TXs).
 * The Flutter app uses `signTransactions` (sign-only) and then
 * submits the signed TX via this endpoint.
 */
wallet.post(
  "/submit-signed",
  requireAuth,
  zValidator("json", submitSignedSchema),
  async (c) => {
    const body = c.req.valid("json");
    const txBytes = Buffer.from(body.transaction, "base64");

    const connection = getConnection();
    try {
      const signature = await connection.sendRawTransaction(txBytes, {
        skipPreflight: false,
        preflightCommitment: "confirmed",
      });

      // Wait for confirmation (with timeout)
      const { blockhash, lastValidBlockHeight } =
        await connection.getLatestBlockhash();
      await connection.confirmTransaction(
        { signature, blockhash, lastValidBlockHeight },
        "confirmed"
      );

      return c.json({
        success: true,
        signature,
      });
    } catch (e: any) {
      const msg = e?.message || e?.toString() || "Unknown error";
      throw createApiError(`Transaction submission failed: ${msg}`, 400);
    }
  }
);

export default wallet;
